### ISSUE TITLE
Restler.exe: No such file or directory

### ISSUE THREAD

**Issue by varunr-uc** [microsoft/restler-fuzzer#128]
https://github.com/microsoft/restler-fuzzer/blob/main/docs/user-guide/Compiling.md
created a directory (mis@mispl-wkstn-87:~/restler_bin)
cloned (git@github.com:microsoft/restler-fuzzer.git) in mis@mispl-wkstn-87:~/restler-fuzzer
ran (python ./build-restler.py --dest_dir <full path to restler_bin above>) in (mis@mispl-wkstn-87:~/restler_bin)
========
while running below command:
mis@mispl-wkstn-87:~/restler_bin
$ restler/Restler.exe compile --api_spec /home/mis/restler-test/openapi.json
output: bash: restler/Restler.exe: No such file or directory

Can you help me out with this. Where exactly i need to compile or generate RESTler grammar or any tutorial to help me out.

**Comment by Luukvdm** [comment]
The file restler/Restler.exe doesnt exist. Maybe try ``dotnet restler/Restler.dll compile`` instead.
Also, since you are using bash, executing .exe files on Linux probably wont work if thats what you are doing.

**Comment by varunr-uc** [comment]
dotnet restler/Restler.dll compile --api_spec /home/mis/restler-test/openapi.json
**output:**
Log share was not specified.  Logs will not be uploaded.
Starting task Compile...

ERROR: Compiler failed. See logs in /home/mis/restler_bin/Compile directory for more information. 

Task Compile failed.
Collecting logs...
The grammar file is not present. Is that im missing any steps?
The results of the above compilation are pasted below.
mis@mispl-wkstn-87:~/restler_bin/Compile
$ ls
config.json       openapi_preprocessed.json    StdErr.txt
defaultDict.json  restler-20210118-104231.log  StdOut.txt

**Comment by varunr-uc** [comment]
> # https://github.com/microsoft/restler-fuzzer/blob/main/docs/user-guide/Compiling.md
> created a directory (mis@mispl-wkstn-87:~/restler_bin) cloned ([git@github.com](mailto:git@github.com):microsoft/restler-fuzzer.git) in mis@mispl-wkstn-87:~/restler-fuzzer
> ran (python ./build-restler.py --dest_dir ) in (mis@mispl-wkstn-87:~/restler_bin)
> while running below command:
> mis@mispl-wkstn-87:~/restler_bin
> $ restler/Restler.exe compile --api_spec /home/mis/restler-test/openapi.json
> output: bash: restler/Restler.exe: No such file or directory
> 
> Can you help me out with this. Where exactly i need to compile or generate RESTler grammar or any tutorial to help me out.

**Comment by varunr-uc** [comment]
Any updates for the above comment?

**Comment by marina-p** [comment]
Hello @varunr-uc,

When the RESTler task (compile, test, fuzz) fails, StdErr.txt should have the error details.  Can you share the contents of this file?

**Comment by varunr-uc** [comment]
Unhandled exception. System.AggregateException: One or more errors occurred. (Could not resolve the path '#/paths/~1search/post/responses/400'.)
 ---> System.InvalidOperationException: Could not resolve the path '#/paths/~1search/post/responses/400'.
   at NJsonSchema.JsonReferenceResolver.ResolveDocumentReference(Object rootObject, String jsonPath)
   at NJsonSchema.JsonReferenceResolver.ResolveReferenceAsync(Object rootObject, String jsonPath, Boolean append)
   at NJsonSchema.JsonReferenceResolver.ResolveReferenceAsync(Object rootObject, String jsonPath)
   at NJsonSchema.JsonSchemaReferenceUtilities.JsonReferenceUpdater.VisitJsonReferenceAsync(IJsonReference reference, String path, String typeNameHint)
   at NJsonSchema.Visitors.AsyncJsonReferenceVisitorBase.VisitAsync(Object obj, String path, String typeNameHint, ISet`1 checkedObjects, Action`1 replacer)
   at NJsonSchema.Visitors.AsyncJsonReferenceVisitorBase.VisitAsync(Object obj, String path, String typeNameHint, ISet`1 checkedObjects, Action`1 replacer)
   at NJsonSchema.Visitors.AsyncJsonReferenceVisitorBase.VisitAsync(Object obj, String path, String typeNameHint, ISet`1 checkedObjects, Action`1 replacer)
   at NJsonSchema.Visitors.AsyncJsonReferenceVisitorBase.VisitAsync(Object obj, String path, String typeNameHint, ISet`1 checkedObjects, Action`1 replacer)
   at NJsonSchema.Visitors.AsyncJsonReferenceVisitorBase.VisitAsync(Object obj, String path, String typeNameHint, ISet`1 checkedObjects, Action`1 replacer)
   at NJsonSchema.Visitors.AsyncJsonReferenceVisitorBase.VisitAsync(Object obj, String path, String typeNameHint, ISet`1 checkedObjects, Action`1 replacer)
   at NJsonSchema.Visitors.AsyncJsonReferenceVisitorBase.VisitAsync(Object obj)
   at NJsonSchema.JsonSchemaReferenceUtilities.JsonReferenceUpdater.VisitAsync(Object obj)
   at NJsonSchema.JsonSchemaReferenceUtilities.UpdateSchemaReferencesAsync(Object rootObject, JsonReferenceResolver referenceResolver, IContractResolver contractResolver)
   at NJsonSchema.Infrastructure.JsonSchemaSerialization.FromJsonAsync[T](String json, SchemaType schemaType, String documentPath, Func`2 referenceResolverFactory, IContractResolver contractResolver)
   at NSwag.OpenApiDocument.FromJsonAsync(String data, String documentPath, SchemaType expectedSchemaType, Func`2 referenceResolverFactory)
   at NSwag.OpenApiDocument.FromFileAsync(String filePath)
   --- End of inner exception stack trace ---
   at Microsoft.FSharp.Control.AsyncResult`1.Commit() in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 350
   at Microsoft.FSharp.Control.AsyncPrimitives.RunSynchronouslyInCurrentThread[a](CancellationToken cancellationToken, FSharpAsync`1 computation) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 882
   at Microsoft.FSharp.Control.AsyncPrimitives.RunSynchronously[T](CancellationToken cancellationToken, FSharpAsync`1 computation, FSharpOption`1 timeout) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 890
   at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T](FSharpAsync`1 computation, FSharpOption`1 timeout, FSharpOption`1 cancellationToken) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 1154
   at Restler.Workflow.swaggerDocs@88-1.Invoke(String fp) in /home/mis/restler-fuzzer/src/compiler/Restler.Compiler/Workflow.fs:line 88
   at Microsoft.FSharp.Primitives.Basics.List.map[T,TResult](FSharpFunc`2 mapping, FSharpList`1 x) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\local.fs:line 248
   at Microsoft.FSharp.Collections.ListModule.Map[T,TResult](FSharpFunc`2 mapping, FSharpList`1 list) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\list.fs:line 75
   at Restler.Workflow.generateGrammarFromSwagger(String grammarOutputDirectoryPath, FSharpOption`1 swaggerDoc, Config config) in /home/mis/restler-fuzzer/src/compiler/Restler.Compiler/Workflow.fs:line 88
   at Restler.Workflow.generateRestlerGrammar(FSharpOption`1 swaggerDoc, Config config) in /home/mis/restler-fuzzer/src/compiler/Restler.Compiler/Workflow.fs:line 233
   at Program.main(String[] argv) in /home/mis/restler-fuzzer/src/compiler/Restler.CompilerExe/Program.fs:line 37

**Comment by varunr-uc** [comment]
Any updates on the above error?

**Comment by stishkin** [comment]
@varunr-uc - is it possible for you to share your swagger specification ? Or at least a subset of swagger so we could repro ?

**Comment by marina-p** [comment]
Hello @varunr-uc,

Unfortunately, we cannot investigate much further without having a (minimal) repro of the reference structure in your spec.  If you have a chance to try on the latest version of RESTler, please share these logs.  Closing the issue until we are able to get more information to debug it further.

Thanks,

Marina

**Comment by castroben** [comment]
When I run the command 
`python ./build-restler.py --dest_dir <full path to restler_bin above>`

the restler_bin directory gets populated by an "engine" subdirectory only.  For some reason, the build does not generate a "restler" subdirectory, a "restler/Restler.exe" or a "restler/Restler.dll" file. 

Because of this, I cannot compile anything. Can someone help me figure out how to complie an api spec?

Thakn you.
