### ISSUE TITLE
demo_server from the tutorial yielding incomplete coverage

### ISSUE THREAD

**Issue by shoaloak** [microsoft/restler-fuzzer#165]
Hi,

When running RESTler on either Linux or Windows, I get incomplete coverage for the tutorial. According to the [README.md](https://github.com/microsoft/restler-fuzzer/blob/main/docs/user-guide/TutorialDemoServer.md), I should achieve a total spec coverage of `5 / 6`.

When running myself, I get `Final Swagger spec coverage: 1 / 6`. Is the demo_server broken?

**Comment by xlx-nju** [comment]
I've met the question as you too. When running RESTler on Windows, I get coverage of `5/6`, but `1/6` on Linux. The log of the demo_server on linux is as follows
```
(venv) [root@n1 demo_server]# python demo_server/app.py 
2021-03-25 06:40:14,826 - __main__ - INFO - >>>>> Starting development server at http://localhost:8888/api/ <<<<<
 * Serving Flask app "app" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
2021-03-25 06:40:14,836 - werkzeug - INFO -  * Running on http://localhost:8888/ (Press CTRL+C to quit)
2021-03-25 06:41:02,450 - werkzeug - INFO - 127.0.0.1 - - [25/Mar/2021 06:41:02] "GET /api/blog/posts HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/root/restler-fuzzer-50efeacd858335bf66a7942b49a7079b102f15df/demo_server/venv/lib/python3.7/site-packages/sqlalchemy/util/_collections.py", line 1008, in __call__
    return self.registry[key]
KeyError: <greenlet.greenlet object at 0x7fad9f9577d8 (otid=0x7fad9f90bf78) current active started main>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/restler-fuzzer-50efeacd858335bf66a7942b49a7079b102f15df/demo_server/venv/lib/python3.7/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/root/restler-fuzzer-50efeacd858335bf66a7942b49a7079b102f15df/demo_server/venv/lib/python3.7/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/root/restler-fuzzer-50efeacd858335bf66a7942b49a7079b102f15df/demo_server/venv/lib/python3.7/site-packages/flask_restplus/api.py", line 584, in error_router
    return original_handler(e)
  File "/root/restler-fuzzer-50efeacd858335bf66a7942b49a7079b102f15df/demo_server/venv/lib/python3.7/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/root/restler-fuzzer-50efeacd858335bf66a7942b49a7079b102f15df/demo_server/venv/lib/python3.7/site-packages/flask/_compat.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/root/restler-fuzzer-50efeacd858335bf66a7942b49a7079b102f15df/demo_server/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/restler-fuzzer-50efeacd858335bf66a7942b49a7079b102f15df/demo_server/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/restler-fuzzer-50efeacd858335bf66a7942b49a7079b102f15df/demo_server/venv/lib/python3.7/site-packages/flask_restplus/api.py", line 584, in error_router
    return original_handler(e)
  File "/root/restler-fuzzer-50efeacd858335bf66a7942b49a7079b102f15df/demo_server/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/root/restler-fuzzer-50efeacd858335bf66a7942b49a7079b102f15df/demo_server/venv/lib/python3.7/site-packages/flask/_compat.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/root/restler-fuzzer-50efeacd858335bf66a7942b49a7079b102f15df/demo_server/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/restler-fuzzer-50efeacd858335bf66a7942b49a7079b102f15df/demo_server/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/restler-fuzzer-50efeacd858335bf66a7942b49a7079b102f15df/demo_server/venv/lib/python3.7/site-packages/flask_restplus/api.py", line 325, in wrapper
    resp = resource(*args, **kwargs)
  File "/root/restler-fuzzer-50efeacd858335bf66a7942b49a7079b102f15df/demo_server/venv/lib/python3.7/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/root/restler-fuzzer-50efeacd858335bf66a7942b49a7079b102f15df/demo_server/venv/lib/python3.7/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/root/restler-fuzzer-50efeacd858335bf66a7942b49a7079b102f15df/demo_server/venv/lib/python3.7/site-packages/flask_restplus/marshalling.py", line 243, in wrapper
    resp = f(*args, **kwargs)
  File "/root/restler-fuzzer-50efeacd858335bf66a7942b49a7079b102f15df/demo_server/demo_server/api/blog/endpoints/posts.py", line 32, in get
    posts_query = Post.query
  File "/root/restler-fuzzer-50efeacd858335bf66a7942b49a7079b102f15df/demo_server/venv/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py", line 514, in __get__
    return type.query_class(mapper, session=self.sa.session())
  File "/root/restler-fuzzer-50efeacd858335bf66a7942b49a7079b102f15df/demo_server/venv/lib/python3.7/site-packages/sqlalchemy/orm/scoping.py", line 128, in __call__
    return self.registry()
  File "/root/restler-fuzzer-50efeacd858335bf66a7942b49a7079b102f15df/demo_server/venv/lib/python3.7/site-packages/sqlalchemy/util/_collections.py", line 1010, in __call__
    return self.registry.setdefault(key, self.createfunc())
  File "/root/restler-fuzzer-50efeacd858335bf66a7942b49a7079b102f15df/demo_server/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 4027, in __call__
    return self.class_(**local_kw)
  File "/root/restler-fuzzer-50efeacd858335bf66a7942b49a7079b102f15df/demo_server/venv/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py", line 138, in __init__
    bind = options.pop('bind', None) or db.engine
  File "/root/restler-fuzzer-50efeacd858335bf66a7942b49a7079b102f15df/demo_server/venv/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py", line 943, in engine
    return self.get_engine()
  File "/root/restler-fuzzer-50efeacd858335bf66a7942b49a7079b102f15df/demo_server/venv/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py", line 962, in get_engine
    return connector.get_engine()
  File "/root/restler-fuzzer-50efeacd858335bf66a7942b49a7079b102f15df/demo_server/venv/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py", line 555, in get_engine
    options = self.get_options(sa_url, echo)
  File "/root/restler-fuzzer-50efeacd858335bf66a7942b49a7079b102f15df/demo_server/venv/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py", line 570, in get_options
    self._sa.apply_driver_hacks(self._app, sa_url, options)
  File "/root/restler-fuzzer-50efeacd858335bf66a7942b49a7079b102f15df/demo_server/venv/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py", line 914, in apply_driver_hacks
    sa_url.database = os.path.join(app.root_path, sa_url.database)
AttributeError: can't set attribute
```
