### ISSUE TITLE
don't swallow errors in the engine

### ISSUE THREAD

**Issue by marina-p** [microsoft/restler-fuzzer#220]
There are many places in the engine, especially on the fuzzing thread, where exceptions are swallowed.  We need to make sure exceptions are reported to be able to quickly diagnose errors.

This work item is opened to fix recently observed cases.  For example: 

        try:
            with open(grammar_path, 'r') as grammar:
                schema_json = json.load(grammar)
        except Exception as err:
            logger.write_to_main(f"Failed to process grammar file: {grammar_path}; {err!s}", print_to_console=True)
            sys.exit(-1)

    except ValueError as err:
        logger.write_to_main(f"Failed to parse grammar file for examples: {err!s}", print_to_console=True)
        return False

**Comment by chakeson** [comment]
Hello, what do you mean by exceptions are swallowed?
Do you want to "raise Exception"?
Or is it with "with" doing "with open(grammar_path, 'r') as (grammar err):" instead?
Or do mean in restler/restler.py on line 506-507 where you have a sys.exit with no logging [link](https://github.com/microsoft/restler-fuzzer/blob/d8210ff7b559f8055218e4cc359347e98e387ff4/restler/restler.py#L506)
Or do mean in restler-fuzzer/restler/engine/core/preprocessing.py  on line 119-144 where there is no general exception [Link](https://github.com/microsoft/restler-fuzzer/blob/d8210ff7b559f8055218e4cc359347e98e387ff4/restler/engine/core/preprocessing.py#L119)

**Comment by marina-p** [comment]
Hello,

The user should see the exception and call stack in the standard error.  Currently, there is no exception and only an error is printed, making it more difficult to diagnose issues.  So, for the fix, if 'raise Exception' modified in one place causes the call stack to be printed, that is a sufficient fix.  If not, you will have to trace if it is being caught again later, and modify those places as well.

**Comment by chakeson** [comment]
Since "raise Exception" will crash the program which might not be desired behaviour alot of the time. A better solution might be "logger.exception()" which depending on how the logger is set up will print to the logfile and the stdout.
The information it prints contains the Traceback with timestamps and the callstack.

<details>
  <summary>Example of logger.exception output</summary>

  2021-05-24 16:23:45,477:__main__:text
  Traceback (most recent call last):
  File "e:\Open Source\restler-fuzzer\test.py", line 34, in <module>
    failure_test()
  File "e:\Open Source\restler-fuzzer\test.py", line 5, in failure_test
    x = 1/0
ZeroDivisionError: division by zero

</details>

**Comment by marina-p** [comment]
Yep, thanks, this is a better solution.
