### ISSUE TITLE
Would you display the details when the compile failed? 

### ISSUE THREAD

**Issue by h0rs3fa11** [microsoft/restler-fuzzer#251]
It's hard to find out the reason of compile failed through restler-fuzzer/Compile/StdErr.txt, this file only contained the exception of source code, It would be better if the error can point to a specific api file.

eg.
```
Unhandled exception. System.Exception: non-array should always have a property name
   at Restler.Compiler.SwaggerVisitors.GenerateGrammarElements.extractPropertyFromObject(String propertyName, JsonObjectType objectType, FSharpOption`1 exampleObj) in /home/horsefall/work/restler-fuzzer/src/compiler/Restler.Compiler/SwaggerVisitors.fs:line 177
   at Restler.Compiler.SwaggerVisitors.declaredPropertyParameters@389.Invoke(KeyValuePair`2 item) in /home/horsefall/work/restler-fuzzer/src/compiler/Restler.Compiler/SwaggerVisitors.fs:line 392
   at Microsoft.FSharp.Collections.Internal.IEnumerator.choose@171.System-Collections-IEnumerator-MoveNext() in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\seq.fs:line 179
   at Microsoft.FSharp.Core.CompilerServices.RuntimeHelpers.takeInner@266[T,TResult](ConcatEnumerator`2 x, Unit unitVar0) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\seqcore.fs:line 268
   at Microsoft.FSharp.Collections.SeqModule.IsEmpty[T](IEnumerable`1 source) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\seq.fs:line 702
   at Restler.Compiler.SwaggerVisitors.generateGrammarElementForSchema(JsonSchema schema, FSharpOption`1 exampleValue, Boolean generateFuzzablePayloadsForExamples, FSharpList`1 parents, FSharpFunc`2 cont) in /home/horsefall/work/restler-fuzzer/src/compiler/Restler.Compiler/SwaggerVisitors.fs:line 479
   at Restler.Compiler.Main.allResponseProperties@637.GenerateNext(IEnumerable`1& next)
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl() in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\seqcore.fs:line 371
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.System-Collections-IEnumerator-MoveNext() in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\seqcore.fs:line 403
   at Microsoft.FSharp.Collections.SeqModule.TryHead[T](IEnumerable`1 source) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\seq.fs:line 1370
   at Restler.Compiler.Main.requestDataSeq$cont@601(Config config, String ep, KeyValuePair`2 m, RequestId requestId, FSharpOption`1 exampleConfig, Unit unitVar) in /home/horsefall/work/restler-fuzzer/src/compiler/Restler.Compiler/Compiler.fs:line 645
   at Restler.Compiler.Main.getRequestData@557-1.GenerateNext(IEnumerable`1& next) in /home/horsefall/work/restler-fuzzer/src/compiler/Restler.Compiler/Compiler.fs:line 601
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl() in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\seqcore.fs:line 371
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.System-Collections-IEnumerator-MoveNext() in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\seqcore.fs:line 403
   at Microsoft.FSharp.Core.CompilerServices.RuntimeHelpers.takeInner@266[T,TResult](ConcatEnumerator`2 x, Unit unitVar0) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\seqcore.fs:line 268
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at Microsoft.FSharp.Collections.SeqModule.ToArray[T](IEnumerable`1 source) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\seq.fs:line 825
   at Restler.Compiler.Main.generateRequestGrammar(FSharpList`1 swaggerDocs, MutationsDictionary dictionary, Config config, FSharpList`1 globalExternalAnnotations, FSharpOption`1 userSpecifiedExamples) in /home/horsefall/work/restler-fuzzer/src/compiler/Restler.Compiler/Compiler.fs:line 704
   at Restler.Workflow.generateGrammarFromSwagger(String grammarOutputDirectoryPath, FSharpOption`1 swaggerDoc, Config config) in /home/horsefall/work/restler-fuzzer/src/compiler/Restler.Compiler/Workflow.fs:line 156
   at Restler.Workflow.generateRestlerGrammar(FSharpOption`1 swaggerDoc, Config config) in /home/horsefall/work/restler-fuzzer/src/compiler/Restler.Compiler/Workflow.fs:line 247
   at Program.main(String[] argv) in /home/horsefall/work/restler-fuzzer/src/compiler/Restler.CompilerExe/Program.fs:line 37

```

**Comment by h0rs3fa11** [comment]
Does anyone know `non-array should always have a property name` means in a swagger file?

**Comment by marina-p** [comment]
Hello @h0rs3fa11,

This means that there is a type for which RESTler expects a property name, but it did not find one in the spec.  Arrays are an exception, because the array element does not have a name.  There may be another case missing.

Could you please build the mp/diag branch and paste what is printed in the exception?  I added more diagnostic info to see which type is failing.

We'll also add the diagnostic on which method and endpoint is failing, but this will take a little more time.

Thanks,

Marina

**Comment by h0rs3fa11** [comment]
It's strange, I compile succeeded after pulling the newest code

**Comment by marina-p** [comment]
That's strange.  Was it an older version, or the commit right before?

(I'd like to keep this issue open until the additional logging is added, so please do not close it.)

Thanks!

**Comment by h0rs3fa11** [comment]
I don't remember the version that I used before. And I will not to close this issue. 
Thank you for your reply!
