### ISSUE TITLE
NullReferenceException in CodeGenerator.fs getRequests

### ISSUE THREAD

**Issue by Daylend** [microsoft/restler-fuzzer#281]
Command run:

> `./Restler compile --api_spec ~/publiclocal3.json`

Crash report:
```Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Restler.CodeGenerator.Python.quoteStringForPythonGrammar@802(String s) in /home/daylend/restler-fuzzer/src/compiler/Restler.Compiler/CodeGenerator.fs:line 804
   at Restler.CodeGenerator.Python.getExamplePrimitiveParameter@823(FSharpOption`1 exv) in /home/daylend/restler-fuzzer/src/compiler/Restler.Compiler/CodeGenerator.fs:line 827
   at Restler.CodeGenerator.Python.formatRestlerPrimitive@823.Invoke(RequestPrimitiveType p) in /home/daylend/restler-fuzzer/src/compiler/Restler.Compiler/CodeGenerator.fs:line 870
   at Microsoft.FSharp.Primitives.Basics.List.mapToFreshConsTail[a,b](FSharpList`1 cons, FSharpFunc`2 f, FSharpList`1 x) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\local.fs:line 241
   at Microsoft.FSharp.Primitives.Basics.List.map[T,TResult](FSharpFunc`2 mapping, FSharpList`1 x) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\local.fs:line 251
   at Microsoft.FSharp.Collections.ListModule.Map[T,TResult](FSharpFunc`2 mapping, FSharpList`1 list) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\list.fs:line 75
   at Restler.CodeGenerator.Python.generatePythonRequest@937(Boolean includeOptionalParameters, FSharpFunc`2 formatRestlerPrimitive, Request request) in /home/daylend/restler-fuzzer/src/compiler/Restler.Compiler/CodeGenerator.fs:line 940
   at Restler.CodeGenerator.Python.getRequests@965.Invoke(Request r) in /home/daylend/restler-fuzzer/src/compiler/Restler.Compiler/CodeGenerator.fs:line 965
   at Microsoft.FSharp.Primitives.Basics.List.mapToFreshConsTail[a,b](FSharpList`1 cons, FSharpFunc`2 f, FSharpList`1 x) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\local.fs:line 241
   at Microsoft.FSharp.Primitives.Basics.List.map[T,TResult](FSharpFunc`2 mapping, FSharpList`1 x) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\local.fs:line 251
   at Microsoft.FSharp.Collections.ListModule.Map[T,TResult](FSharpFunc`2 mapping, FSharpList`1 list) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\list.fs:line 75
   at Restler.CodeGenerator.Python.generatePythonGrammar@979.GenerateNext(IEnumerable`1& next) in /home/daylend/restler-fuzzer/src/compiler/Restler.Compiler/CodeGenerator.fs:line 986
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl() in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\seqcore.fs:line 371
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.System-Collections-IEnumerator-MoveNext() in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\seqcore.fs:line 403
   at Microsoft.FSharp.Collections.SeqModule.ToList[T](IEnumerable`1 source) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\seq.fs:line 546
   at Restler.CodeGenerator.Python.generateCode(GrammarDefinition grammar, Boolean includeOptionalParameters, FSharpFunc`2 write) in /home/daylend/restler-fuzzer/src/compiler/Restler.Compiler/CodeGenerator.fs:line 1011
   at Restler.Workflow.generatePython(String grammarOutputDirectoryPath, Config config, GrammarDefinition grammar) in /home/daylend/restler-fuzzer/src/compiler/Restler.Compiler/Workflow.fs:line 27
   at Restler.Workflow.generateRestlerGrammar(FSharpOption`1 swaggerDoc, Config config) in /home/daylend/restler-fuzzer/src/compiler/Restler.Compiler/Workflow.fs:line 253
   at Program.main(String[] argv) in /home/daylend/restler-fuzzer/src/compiler/Restler.CompilerExe/Program.fs:line 37
```
I don't think I can include the api_spec file. However, I've run the spec through the swagger.io validator and it appears to be valid.

Using the quick start command attempts to run the generated grammar file, resulting in: 
> Cannot import grammar: module 'grammar' has no attribute 'req_collection'

Thanks!

**Comment by marina-p** [comment]
Hello @Daylend ,

Thanks for the bug report. There should be one more line in the standard error output, could you please add it?  The exception that was thrown is missing in the description. 

Thanks,

Marina

**Comment by marina-p** [comment]
This is a null deref bug when an example in the spec has type string and is null.
