### ISSUE TITLE
Cache dir creation fails when using a non-existing user

### ISSUE THREAD

**Issue by rhtenhove** [microsoft/restler-fuzzer#295]
When running this using Docker under another user than `root`, it can't run because it can't create the cache directory.

I can't see a way to change that directory. Perhaps a good fallback is to create it in `/tmp` when it is unable to create it, or just allow disabling cache.

For example:

```shell
docker run -ti -u $UID:$GID -v "$PWD":/pwd --workdir /pwd mcr.microsoft.com/restlerfuzzer/restler:v8.0.0

$ dotnet /RESTler/restler/Restler.dll compile --api_spec openapi.yml
Failed to create directory //.config/microsoft/restler.  Re-trying for 2 more attempts...
Failed to create directory //.config/microsoft/restler.  Re-trying for 1 more attempts...
Failed to create directory //.config/microsoft/restler.  Re-trying for 0 more attempts...
Unhandled exception. System.UnauthorizedAccessException: Access to the path '/.config/microsoft/restler' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at Restler.Driver.Files.createDirectoryWithRetries(String targetPath, Int32 retryCount, FSharpList`1 exceptions, TimeSpan delay, Boolean checkIfExists) in D:\a\1\s\src\driver\Files.fs:line 18
   at Restler.Driver.Files.createDirectoryWithRetries(String targetPath, Int32 retryCount, FSharpList`1 exceptions, TimeSpan delay, Boolean checkIfExists) in D:\a\1\s\src\driver\Files.fs:line 24
   at Restler.Driver.Files.createDirectoryWithRetries(String targetPath, Int32 retryCount, FSharpList`1 exceptions, TimeSpan delay, Boolean checkIfExists) in D:\a\1\s\src\driver\Files.fs:line 24
   at Restler.Driver.Files.createDirectoryWithRetries(String targetPath, Int32 retryCount, FSharpList`1 exceptions, TimeSpan delay, Boolean checkIfExists) in D:\a\1\s\src\driver\Files.fs:line 24
   at Restler.Driver.Telemetry.getMachineIdFilePath() in D:\a\1\s\src\driver\Telemetry.fs:line 36
   at Program.main(String[] argv) in D:\a\1\s\src\driver\Program.fs:line 754
Aborted
```

**Comment by marina-p** [comment]
Thanks for reporting this, we will look into this ASAP.

**Comment by marina-p** [comment]
This dir is only used for persisting a unique ID for our telemetry data, it is not used for storing the Compile directories etc. (those are placed in the current working directory). 

Using /tmp instead if creating the directory in the cache fails seems reasonable.

**Comment by marina-p** [comment]
This is now fixed in mcr.microsoft.com/restlerfuzzer/restler:v8.2.0
