### ISSUE TITLE
status code: 400 bad request

### ISSUE THREAD

**Issue by xlx-nju** [microsoft/restler-fuzzer#315]
When I use restler, almost all the returned status codes are 400 bad request, is that because too many query parameters? is that normal?

shell script
`$RESTler_DIR"/"Restler fuzz --grammar_file $WORKING_DIR/Compile/grammar.py --time_budget 1 --dictionary_file $WORKING_DIR/Compile/dict.json  --settings $WORKING_DIR/Compile/engine_settings.json --no_ssl --token_refresh_interval 100000 --token_refresh_command /auth`

network.testing.*.txt output
`2021-04-20 04:01:03.300: Sending: 'GET /api/v4/projects?archived=true&id_after=0&id_before=0&last_activity_after=6/25/2019 12:00:00 AM&last_activity_before=6/25/2019 12:00:00 AM&membership=true&min_access_level=0&order_by=id&owned=true&repository_storage=fuzzstring&search_namespaces=true&search=fuzzstring&simple=true&sort=asc&starred=true&statistics=true&visibility=public&with_custom_attributes=true&with_issues_enabled=true&with_merge_requests_enabled=true&with_programming_language=fuzzstring HTTP/1.1\r\nAccept: application/json\r\nHost: localhost:30000\r\n_OMITTED_AUTH_TOKEN_\r\nContent-Length: 0\r\nUser-Agent: restler/7.3.0\r\n\r\n'

2021-04-20 04:02:08.322: Received: 'HTTP/1.1 400 Bad Request\r\nServer: nginx\r\nDate: Tue, 20 Apr 2021 04:01:03 GMT\r\nContent-Type: text/plain; charset=utf-8\r\nTransfer-Encoding: chunked\r\nConnection: keep-alive\r\n\r\nf\r\n400 Bad Request\r\n0\r\n\r\n'

`

**Comment by marina-p** [comment]
Hello @xlx-nju,

Yes, this is possibly due to the fact that RESTler-generated values for the query parameters are not valid or not all parameters can be used together (you should investigate this for one endpoint+method just to make sure).  

As a potential workaround, can you please try to add the following to the engine settings file and see if it improves the coverage (this will cause just required query parameters to be tested, in addition to all which is the current default. ):

  "max_combinations": 100,
  "test_combinations_settings": {
    "query_param_combinations" : "required"
}

**Comment by mbiuki** [comment]
Note, due to #320 and #284, looks like below should be a valid construct:
```json
"test_combinations_settings": 
{
 "header_param_combinations": 
  {
 	"max_combinations": 10,
 	"param_kind": "optional"
  },
 "query_param_combinations": 
  {
 	"max_combinations": 15,
 	"param_kind": "required"
  },
 "example_payloadds":
  {
 	"payload_kind": "all"
  }
},
```
@marina-p, please confirm if the above construct is correct to be placed in `restler_user_settings.json`?
Otherwise, the compiler will fail with this error:
```bash
$ cat EngineStdOut.txt
Initializing: Garbage collection every 30 seconds.
No checkpoints used at this phase
Terminating garbage collection. Waiting for max 300 seconds.
Traceback (most recent call last):
  File "/usr/local/bin/restler_bin/engine/engine/core/fuzzer.py", line 42, in run
    self._num_total_sequences = driver.generate_sequences(
  File "/usr/local/bin/restler_bin/engine/engine/core/driver.py", line 618, in generate_sequences
    logger.print_req_collection_stats(
  File "/usr/local/bin/restler_bin/engine/utils/logger.py", line 683, in print_req_collection_stats
    val = r.num_combinations(candidate_values_pool)
  File "/usr/local/bin/restler_bin/engine/engine/core/requests.py", line 908, in num_combinations
    for combination in self.render_iter(candidate_values_pool):
  File "/usr/local/bin/restler_bin/engine/engine/core/requests.py", line 834, in render_iter
    for req in self.get_schema_combinations():
  File "/usr/local/bin/restler_bin/engine/engine/core/requests.py", line 624, in get_schema_combinations
    for hpc in self.get_header_param_combinations(header_param_combinations):
  File "/usr/local/bin/restler_bin/engine/engine/core/requests.py", line 1019, in get_header_param_combinations
    for param_list in param_combinations.get_param_combinations(self, header_param_combinations_setting,
  File "/usr/local/bin/restler_bin/engine/engine/fuzzing_parameters/param_combinations.py", line 45, in get_param_combinations
    max_combinations = Settings().max_combinations
NameError: name 'Settings' is not defined

```

**Comment by marina-p** [comment]
@mbiuki 

Yes, the above is valid.  However, the error above is due to a bug that will be fixed shortly (it should be possible to omit max_combinations).

**Comment by Sriram7891** [comment]
Just to clarify, is it correct to say that response code with "500" is only considered as bug? any other error code with 400, 405, 415, etc are considered only failure and not a bug? Please clarify

**Comment by PatGod** [comment]
Yes, your statement is correct.
