### ISSUE TITLE
RESTler Docker fails to run the fuzzer

### ISSUE THREAD

**Issue by mbiuki** [microsoft/restler-fuzzer#371]
In RESTler container, I face the issues that are reported https://github.com/microsoft/restler-fuzzer/issues/304#issue-977898141

Here are the steps:

1. `docker run -ti -v /PATH/container:/pwd --workdir /pwd mcr.microsoft.com/restlerfuzzer/restler:v8.0.0`
2. `/pwd # dotnet ../RESTler/restler/Restler.dll compile --api_spec openapi.yaml `
```
Starting task Compile...
Task Compile succeeded.
Collecting logs...
```
3. `apk-add python3`, with some additional options that I needed: `apk-add curl`  and `pip install jsbeautifier`
 4. `/pwd # dotnet ../RESTler/restler/Restler.dll compile config.json` 

```
Starting task Compile...

ERROR: Compiler failed. See logs in /pwd/Compile directory for more information. 

Task Compile failed.
Collecting logs...
/pwd # cd Compile/
/pwd/Compile # cat StdErr.txt
Unhandled exception. System.ArgumentException: Could not read dictionary: ERROR: Cannot deserialize mutations dictionary.  An exception occurred during deserialization: Newtonsoft.Json.JsonSerializationException: Could not find member 'restler_custom_payload_query' on object of type 'MutationsDictionary'. Path 'restler_custom_payload_query', line 29, position 35.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolvePropertyAndCreatorValues(JsonObjectContract contract, JsonProperty containerProperty, JsonReader reader, Type objectType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters(JsonReader reader, JsonObjectContract contract, JsonProperty containerProperty, ObjectConstructor`1 creator, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateNewObject(JsonReader reader, JsonObjectContract objectContract, JsonProperty containerMember, JsonProperty containerProperty, String id, Boolean& createdFromNonDefaultCreator)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Microsoft.FSharpLu.Json.Compact.tryDeserializeFile[T](String file)
   at Restler.Workflow.generateGrammarFromSwagger(String grammarOutputDirectoryPath, FSharpOption`1 swaggerDoc, Config config) in D:\a\1\s\src\compiler\Restler.Compiler\Workflow.fs:line 131
   at Restler.Workflow.generateRestlerGrammar(FSharpOption`1 swaggerDoc, Config config) in D:\a\1\s\src\compiler\Restler.Compiler\Workflow.fs:line 247
   at Program.main(String[] argv) in D:\a\1\s\src\compiler\Restler.CompilerExe\Program.fs:line 37

```

- Removed `restler_custom_payload_query` from `dict.json`, and it worked!

```
Starting task Compile...
Task Compile succeeded.
Collecting logs...
```

8.	`dotnet ../RESTler/restler/Restler.dll fuzz --grammar_file Compile/grammar.py --settings restler_user_settings.json --dictionary_file dict.json --no_results_analyzer`

```
Starting task Fuzz...
Using python: 'python3' (Python 3.8.10)

ERROR: Restler engine failed. See logs in /pwd/Fuzz directory for more information. 

Task Fuzz failed.
Collecting logs...
/pwd # 
/pwd # cd Fuzz/
/pwd/Fuzz # ls
EngineStdErr.txt             EngineStdOut.txt             RestlerResults               restler-20211008-093016.log
/pwd/Fuzz # cat EngineStdOut.txt 
Initializing: Garbage collection every 30 seconds.
No checkpoints used at this phase
2021-10-08 21:30:17.879: Generation: 1 
Terminating garbage collection. Waiting for max 300 seconds.
Traceback (most recent call last):
  File "/RESTler/engine/engine/core/fuzzer.py", line 42, in run
    self._num_total_sequences = driver.generate_sequences(
  File "/RESTler/engine/engine/core/driver.py", line 695, in generate_sequences
    seq_collection = render(seq_collection, fuzzing_pool, checkers, generation, global_lock)
  File "/RESTler/engine/engine/core/driver.py", line 320, in render_sequential
    valid_renderings = render_one(seq_collection[ith], ith, checkers, generation, global_lock)
  File "/RESTler/engine/engine/core/driver.py", line 207, in render_one
    renderings = current_seq.render(candidate_values_pool, global_lock)
  File "/RESTler/engine/engine/core/sequences.py", line 323, in render
    CUSTOM_LOGGING(self, candidate_values_pool)
  File "/RESTler/engine/utils/logger.py", line 475, in custom_network_logging
    primitive, values, default_val = format_request_block(request.request_id, request_block, candidate_values_pool)
  File "/RESTler/engine/utils/logger.py", line 853, in format_request_block
    values = candidate_values_pool.get_candidate_values(primitive, request_id=request.request_id, tag=current_fuzzable_tag, quoted=quoted)
NameError: name 'request' is not defined

/pwd/Fuzz #
```

- Removed `custom_payload_header` from `dict.json`, and it worked!

`restler_custom_payload_query` and `custom_payload_header` must be removed from the dict.json to get the fuzz container to work. 

Is it possible to add the latest and greatest RESTler engine to the Docker so we do not face those issues and can still use the updated attributes for dict.json? Thanks.

**Comment by marina-p** [comment]
Hello @mbiuki,

The 8.1.0 image is published now.  Please confirm this new image resolves the above error for you.

Thanks,
Marina
