### ISSUE TITLE
Question: How to use request examples correctly?

### ISSUE THREAD

**Issue by c7h** [microsoft/restler-fuzzer#442]
Hello,

I have a Producer Endpoint which throws an error just by using the specification. This is very annoying, because all subsequent sequences cannot be tested.
I would like to improve the coverage with the help of an example, but I do not succeed.

The producer endpoint looks something like this:

![image](https://user-images.githubusercontent.com/2639206/149388898-af24fedc-6c4d-486e-b87c-ddb5d905aec0.png)

I have added the appropriate request into the _examples.json_, which in turn is linked in the compiler configuration by _ExampleConfigFilePath_: 

```
{
  "paths": {
    "/nfinstances/{nfInstanceId}": {
      "put": {
        "one": {
          "parameters": {
            "nfInstanceId": "dead3f64-5717-4562-b3fc-2c963f66afa6",
            "nfInstanceName": "string",
            "nfType": "NRF",
            "nfStatus": "REGISTERED",
            "heartBeatTimer": 1,
            "plmnList": [
              {
                "mcc": "127",
                "mnc": "49"
              }
            ],
            "snpnList": [
              {
                "mcc": "123",
                "mnc": "48",
                "nid": "string"
              }
            ],
            "sNssais": [
              {
                "sst": "255",
                "sd": "string",
                "sdRanges": [
                  {
                    "start": "string",
                    "end": "string"
                  }
                ],
                "wildcardSd": false
              }
            ]
          }
        }
      }
    }
  }
}
```

After recompiling, I expect that the example sequence is now mapped into _grammar.py_, and will be used whenever a new resource is to be created. Unfortunately, I don't see any effect on the result of the compile operation. 

The section of the spec looks like this: 

```yaml
...
    put:
      summary: Register a new NF Instance
      operationId: RegisterNFInstance
      tags:
        - NF Instance ID (Document)
      parameters:
        - name: nfInstanceID
          in: path
          required: true
          description: Unique ID of the NF Instance to register
          schema:
            $ref: "#/components/schemas/NFProfile/properties/nfInstanceId"
            x-miro: TS29571_CommonData.yaml#/components/schemas/NfInstanceId
        - name: Content-Encoding
          in: header
          description: Content-Encoding, described in IETF RFC 7231
          schema:
            type: string
        - name: Accept-Encoding
          in: header
          description: Accept-Encoding, described in IETF RFC 7231
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NFProfile"
        required: true
...
```

Unlike the RESTler example where body parameters are found in the parameters section, the parameters in this example are in the _requestBody_ section. 

Am I missing something important?

Greetings and thanks for your help,
Christoph

**Comment by marina-p** [comment]
Hello Christoph,

Just in case: please make sure you are using the latest RESTler, because we recently fixed an issue with ```requestBody```, and this change is not present in the latest version pushed to the container.

With the latest RESTler, the problem is that the example has to differentiate which parameters are part of the request body.  This can be done by putting them into a ```__body__``` property (special RESTler examples keyword) as follows (just a guess as to which ones are part of the body):

```
{
    "nfInstanceId": "dead3f64-5717-4562-b3fc-2c963f66afa6",
    "__body__": {
        "nfInstanceName": "string",
        "nfType": "NRF",
        "nfStatus": "REGISTERED",
        "heartBeatTimer": 1,
        "plmnList": [
            {
                "mcc": "127",
                "mnc": "49"
            }
        ],
        "snpnList": [
            {
                "mcc": "123",
                "mnc": "48",
                "nid": "string"
            }
        ],
        "sNssais": [
            {
                "sst": "255",
                "sd": "string",
                "sdRanges": [
                    {
                        "start": "string",
                        "end": "string"
                    }
                ],
                "wildcardSd": false
            }
        ]
    }
}

```

Please let me know if this does not resolve your issue.

Thanks,

Marina

**Comment by c7h** [comment]
Thanks for your answer.
In fact I was using an older version of RESTler. I upgraded and put the body parameters in the `__body__` argument in my example:


examples.json:
```
{
  "paths": {
    "/nf-instances/{nfInstanceID}": {
      "put": {
        "1": "/workdir/examples/put_nfinstance.json"
      }
    }
  }
}
```
put_nfinstance.json
```
{
    "parameters": {
        "nfInstanceId": "dead3f64-5717-4562-b3fc-2c963f66afa6",
        "__body__": {
            "nfInstanceName": "string",
            "nfType": "NRF",
            "nfStatus": "REGISTERED",
            "heartBeatTimer": 1,
            "plmnList": [
                {
                    "mcc": "127",
                    "mnc": "49"
                }
            ],
            "snpnList": [
                {
                    "mcc": "123",
                    "mnc": "48",
                    "nid": "string"
                }
            ],
            "sNssais": [
                {
                    "sst": "255",
                    "sd": "string",
                    "sdRanges": [
                        {
                            "start": "string",
                            "end": "string"
                        }
                    ],
                    "wildcardSd": false
                }
            ]
        }
    }
}
```

I'm now receiving a compile error:

`Unhandled exception. System.AggregateException: One or more errors occurred. (The input sequence was empty. (Parameter 'source'))`

I think I am close to the solution but I cannot find the error in my example. Am I missing something in the above definition?

Greetings,
Christoph

**Comment by marina-p** [comment]
Hello,

This looks like you have hit a bug.  Could you please share the full call stack from StdErr.txt (and if possible the definition of NFProfile or a smaller repro for the error)?

Thanks,

Marina

**Comment by c7h** [comment]
Hi Maria, 
sure, this is the compiler output: 


```
Unhandled exception. System.AggregateException: One or more errors occurred. (The input sequence was empty. (Parameter 'source'))
 ---> System.ArgumentException: The input sequence was empty. (Parameter 'source')
   at Microsoft.FSharp.Collections.SeqModule.Head[T](IEnumerable`1 source) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\seq.fs:line 1364
   at Restler.Compiler.Main.Parameters.pathParameters@435-1.Invoke(String part) in /home/c7h/workspace/master/restler-fuzzer/src/compiler/Restler.Compiler/Compiler.fs:line 477
   at Microsoft.FSharp.Collections.Internal.IEnumerator.choose@171.System-Collections-IEnumerator-MoveNext() in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\seq.fs:line 179
   at Microsoft.FSharp.Collections.Internal.IEnumerator.map@75.DoMoveNext(b& curr) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\seq.fs:line 81
   at Microsoft.FSharp.Collections.Internal.IEnumerator.MapEnumerator`1.System-Collections-IEnumerator-MoveNext() in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\seq.fs:line 68
   at Microsoft.FSharp.Core.CompilerServices.RuntimeHelpers.takeOuter@273[T,TResult](ConcatEnumerator`2 x, Unit unitVar0) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\seqcore.fs:line 274
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at Microsoft.FSharp.Collections.SeqModule.ToArray[T](IEnumerable`1 source) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\seq.fs:line 825
   at Restler.Dependencies.generatedSuffixes@1311.Invoke(Tuple`2 tupledArg) in /home/c7h/workspace/master/restler-fuzzer/src/compiler/Restler.Compiler/Dependencies.fs:line 1313
   at Microsoft.FSharp.Collections.ArrayModule.Parallel.Map@1317-3.Invoke(Int32 i) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\array.fs:line 1318
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.For(Int32 fromInclusive, Int32 toExclusive, Action`1 body)
   at Microsoft.FSharp.Collections.ArrayModule.Parallel.Map[T,TResult](FSharpFunc`2 mapping, T[] array) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\array.fs:line 1317
   at Restler.Dependencies.extractDependencies(Tuple`2[] requestData, IEnumerable`1 globalAnnotations, MutationsDictionary customDictionary, Boolean queryDependencies, Boolean bodyDependencies, Boolean headerDependencies, Boolean allowGetProducers, Boolean dataFuzzing, FSharpMap`2 perResourceDictionaries, FSharpOption`1 namingConvention) in /home/c7h/workspace/master/restler-fuzzer/src/compiler/Restler.Compiler/Dependencies.fs:line 1308
   at Restler.Compiler.Main.generateRequestGrammar(FSharpList`1 swaggerDocs, MutationsDictionary dictionary, Config config, FSharpList`1 globalExternalAnnotations, FSharpList`1 userSpecifiedExamples) in /home/c7h/workspace/master/restler-fuzzer/src/compiler/Restler.Compiler/Compiler.fs:line 1248
   at Restler.Workflow.generateGrammarFromSwagger(String grammarOutputDirectoryPath, FSharpOption`1 swaggerDoc, FSharpOption`1 specMetadata, Config config) in /home/c7h/workspace/master/restler-fuzzer/src/compiler/Restler.Compiler/Workflow.fs:line 179
   at Restler.Workflow.generateRestlerGrammar(FSharpOption`1 swaggerDoc, Config config) in /home/c7h/workspace/master/restler-fuzzer/src/compiler/Restler.Compiler/Workflow.fs:line 270
   at Program.main(String[] argv) in /home/c7h/workspace/master/restler-fuzzer/src/compiler/Restler.CompilerExe/Program.fs:line 37
```

I hope this helps to figure out a solution, I would really like to get the examples working.

Greetings and Thanks,
Christoph

**Comment by marina-p** [comment]
Thank you, yes the call stack is helpful.

I did not catch this before - your spec parameter is named ```nfInstanceID``` while in the example it is ```nfInstanceId``` (casing difference).  If you change the example key to have the same name as declared in the spec, this crash should go away.  

(The branch 'mp/crashfix' has the fix, it should be merged later today.)

Thanks,

Marina

**Comment by c7h** [comment]
Thank you a lot for this fix! This solved my problem. I can now add examples.
