### ISSUE TITLE
System.Exception: Could not find path to RESTler engine

### ISSUE THREAD

**Issue by divyakrishnankutty** [microsoft/restler-fuzzer#454]
Compilation worked:

Starting task Compile...
Task Compile succeeded.
Collecting logs...

** smoketest fails with exception:**

Starting task Test...

ERROR: Task Test failed.  Exception: System.Exception: Could not find path to RESTler engine.  Please re-install RESTler or contact support.
   at Program.Fuzz.runRestlerEngine@273-1.Invoke(String m) in /Users/<username>/Projects/restler-fuzzer/src/driver/Program.fs:line 273
   at Program.Fuzz.runRestlerEngine@272.Invoke(Unit unitVar) in /Users/<username>/Projects/restler-fuzzer/src/driver/Program.fs:line 273
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 398
   at Microsoft.FSharp.Control.AsyncPrimitives.unitAsync@589.Invoke(AsyncActivation`1 ctxt) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 589
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 109

Task Test failed.
Collecting logs...

**Comment by marina-p** [comment]
Hello @divyakrishnankutty,

In the RESTler bin folder, do you see the "engine" folder?  If not, could you please share the output of the following commands:

> python --version
> python .\build-restler.py  --dest_dir <your destination dir> --compile_type engine

This may be the same issue as mentioned at the end of #440, it appears to be recent and we are still tracking down the cause.

Thanks,

Marina

**Comment by marina-p** [comment]
One guess: this could be caused by recent changes to the build script.  It would be very helpful for the investigation if you could sync to this earlier commit to see if the issue is resolved: https://github.com/microsoft/restler-fuzzer/commit/7eba32cd37e54e150197bb63cd540c318350d394


Thanks,

Marina

**Comment by divyakrishnankutty** [comment]
Hi Marina,

I do not have the engine folder under bin.

root@<host_name>:/home/<username>/demo/restler_bin# ls
compiler  restler  resultsAnalyzer

Here are the details,

--compile_type engine fails,

Testing compilation of Python files...
Copying all python files...
Build failed!
Exit code: 127
b'/bin/sh: 1: python: not found\n'
Removing engine compilation build directory...


**python version**

python3
Python 3.8.10 (default, Jun  2 2021, 10:49:15) 
[GCC 9.4.0] on linux

Code base have been updated to latest - #455

**Comment by marina-p** [comment]
Thank you for the repro information.  The script defaults to 'python' for this step - it needs to be updated to try both 'python' and 'python3'.  

Could you please try the following workaround (additional argument ```--python_path``` below):

>python .\build-restler.py --dest_dir --compile_type engine  --python_path <full_path_to_python3>

Thanks,

Marina

**Comment by divyakrishnankutty** [comment]
Hey Marina, 

Providing explicit python path helped.

restler-fuzzer# python3 ./build-restler.py --dest_dir ../restler_bin/ --compile_type engine --python_path /usr/bin/python3
Generating a new RESTler binary drop...
Testing compilation of Python files...
Copying all python files...
Removing engine compilation build directory...
Copying all python files...

**Comment by srinat999** [comment]
Hello @divyakrishnankutty @marina-p,

Did you manage to solve this problem? I am hitting the same issue as well. The Build goes through fine for me but the engine directory is empty although it is created. 

```
restler-fuzzer (main) > python3 ./build-restler.py --dest_dir ./restler_bin --compile_type engine --python_path /usr/bin/python3
Generating a new RESTler binary drop...
Testing compilation of Python files...
Copying all python files...
Removing engine compilation build directory...
Copying all python files...
```

Starting the restler-quick-start.py complains that it cannot find RESTler Engine

```
Restler Information: 0 : Starting task Test...
    DateTime=2022-03-03T12:52:53.2081320Z
Restler Error: 0 : Could not find path to RESTler engine.  Please re-install RESTler or contact support.
    DateTime=2022-03-03T12:52:53.2573020Z
Restler Error: 0 : Task Test failed.  Exception: System.Exception: Could not find path to RESTler engine.  Please re-install RESTler or contact support.
   at Program.Fuzz.runRestlerEngine@273-1.Invoke(String m) in  /git/restler-fuzzer/src/driver/Program.fs:line 273
   at Program.Fuzz.runRestlerEngine@272.Invoke(Unit unitVar) in /git/restler-fuzzer/src/driver/Program.fs:line 273
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 398
   at Microsoft.FSharp.Control.AsyncPrimitives.unitAsync@589.Invoke(AsyncActivation`1 ctxt) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 589
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 109
    DateTime=2022-03-03T12:52:53.2834230Z
Restler Information: 0 : Task Test failed.
    DateTime=2022-03-03T12:52:53.2865580Z
Restler Information: 0 : Collecting logs...
    DateTime=2022-03-03T12:52:53.2918160Z
```

I am running this on a Mac, version 11.6.3 with Python 3.9.9
