### ISSUE TITLE
Restler fuzz crashes 

### ISSUE THREAD

**Issue by jbauernberger** [microsoft/restler-fuzzer#474]
Hi,

using restler-fuzzer from `v8.3.0-19-g2f48d69` my REST API returns the following response which crashes the fuzzer:

```
    HTTP/1.1 400 Bad Request\r\n
        Status Code: 400
    Connection: close\r\n
    Content-Type: application/json\r\n
    X-Request-ID: 117fe196-ca84-4744-a309-4404ae64d965\r\n
    \r\n

{"errorCode":"0","message":"","debugInformation":""}
```

the `EngineStdOut.txt` has:

```
Initializing: Garbage collection every 30 seconds.
2022-02-17 12:53:48.087: Generation: 1
2022-02-17 12:53:49.801: Generation: 2
Terminating garbage collection. Waiting for max 300 seconds.
Traceback (most recent call last):
  File "/home/joachim/src/restler-fuzzer/restler_bin/engine/engine/core/fuzzer.py", line 42, in run
    self._num_total_sequences = driver.generate_sequences(
  File "/home/joachim/src/restler-fuzzer/restler_bin/engine/engine/core/driver.py", line 698, in generate_sequences
    seq_collection = render(seq_collection, fuzzing_pool, checkers, generation, global_lock)
  File "/home/joachim/src/restler-fuzzer/restler_bin/engine/engine/core/driver.py", line 320, in render_sequential
    valid_renderings = render_one(seq_collection[ith], ith, checkers, generation, global_lock)
  File "/home/joachim/src/restler-fuzzer/restler_bin/engine/engine/core/driver.py", line 207, in render_one
    renderings = current_seq.render(candidate_values_pool, global_lock)
  File "/home/joachim/src/restler-fuzzer/restler_bin/engine/engine/core/sequences.py", line 382, in render
    prev_response = request_utilities.send_request_data(prev_rendered_data)
  File "/home/joachim/src/restler-fuzzer/restler_bin/engine/engine/core/request_utilities.py", line 282, in send_request_data
    success, response = sock.sendRecv(rendered_data,
  File "/home/joachim/src/restler-fuzzer/restler_bin/engine/engine/transport_layer/messaging.py", line 101, in sendRecv
    response = HttpResponse(self._recvResponse(req_timeout_sec, http_method_name))
  File "/home/joachim/src/restler-fuzzer/restler_bin/engine/engine/transport_layer/messaging.py", line 292, in _recvResponse
    data += decode_buf(buf)
  File "/home/joachim/src/restler-fuzzer/restler_bin/engine/engine/transport_layer/messaging.py", line 215, in decode_buf
    return buf.decode(UTF8)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc3 in position 6734: unexpected end of data
```

From Fuzz/restler-*.log

```
Restler Information: 0 : (12383) python3 -B "/home/joachim/src/restler-fuzzer/restler_bin/restler/../engine/restler.py" --restler_grammar "/home/joachim/src/restler-fuzzer/Compile/grammar.py" --custom_mutations "/home/joachim/src/restler-fuzzer/Compile/dict.json" --set_version 8.3.0  --token_refresh_interval 6000 --token_refresh_cmd "/home/joachim/src/restler-fuzzer/token_get.sh" --producer_timing_delay 1 --no_ssl  --path_regex language-files --settings "/home/joachim/src/restler-fuzzer/Compile/engine_settings.json" --enable_checkers * --disable_checkers namespacerule --time_budget 0.500000 --target_ip 10.13.0.162 --target_port 8080 --include_user_agent --no_tokens_in_logs t --garbage_collection_interval 30 --fuzzing_mode bfs-fast exited with code: 255
```

any ideas?

thanks!

**Comment by jbauernberger** [comment]
that got rid of the crash! Thank you Marina 🙏

**Comment by marina-p** [comment]
Great, thanks for confirming.  

Re-naming the issue and adding more notes for what the fix should be.

**Comment by marina-p** [comment]
RESTler should not crash in this case.  Instead, it should report the error in the spec coverage file.
