### ISSUE TITLE
Unhandled exception. System.Exception: non-array should always have a property name.  Property type: String

### ISSUE THREAD

**Issue by rpbc86** [microsoft/restler-fuzzer#489]
Unhandled exception. System.Exception: non-array should always have a property name.  Property type: String
   at Restler.Compiler.SwaggerVisitors.GenerateGrammarElements.extractPropertyFromObject(String propertyName, JsonObjectType objectType, FSharpOption`1 exampleObj) in C:\_Projects\DCS-RFID-ZIN52-SecurityTesting\microsoft_restler_fuzzer\restler-fuzzer-main\src\compiler\Restler.Compiler\SwaggerVisitors.fs:line 295
   at Restler.Compiler.SwaggerVisitors.declaredPropertyParameters@610.Invoke(KeyValuePair`2 item) in C:\_Projects\DCS-RFID-ZIN52-SecurityTesting\microsoft_restler_fuzzer\restler-fuzzer-main\src\compiler\Restler.Compiler\SwaggerVisitors.fs:line 613
   at Microsoft.FSharp.Collections.Internal.IEnumerator.choose@171.System-Collections-IEnumerator-MoveNext() in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\seq.fs:line 179
   at Microsoft.FSharp.Core.CompilerServices.RuntimeHelpers.takeInner@266[T,TResult](ConcatEnumerator`2 x, Unit unitVar0) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\seqcore.fs:line 268
   at Microsoft.FSharp.Collections.SeqModule.oneStepTo@987[T](IEnumerable`1 source, List`1 prefix, FSharpRef`1 enumeratorR, Int32 i) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\seq.fs:line 996
   at Microsoft.FSharp.Collections.SeqModule.action@4164-1[T](IEnumerable`1 source, List`1 prefix, FSharpRef`1 enumeratorR, Int32 i, Unit unitVar0) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\seq.fs:line 1011
   at Microsoft.FSharp.Collections.SeqModule.result@1003.Invoke(Int32 i)
   at Microsoft.FSharp.Collections.Internal.IEnumerator.unfold@205.DoMoveNext(b& curr) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\seq.fs:line 207
   at Microsoft.FSharp.Collections.Internal.IEnumerator.MapEnumerator`1.System-Collections-IEnumerator-MoveNext() in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\seq.fs:line 68
   at Microsoft.FSharp.Collections.SeqModule.ToList[T](IEnumerable`1 source) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\seq.fs:line 546
   at Restler.Compiler.SwaggerVisitors.generateGrammarElementForSchema(JsonSchema schema, FSharpOption`1 exampleValue, Boolean generateFuzzablePayloadsForExamples, Boolean trackParameters, FSharpOption`1 jsonPropertyMaxDepth, Boolean isRequired, Boolean isReadOnly, FSharpList`1 parents, SchemaCache schemaCache, FSharpFunc`2 cont) in C:\_Projects\DCS-RFID-ZIN52-SecurityTesting\microsoft_restler_fuzzer\restler-fuzzer-main\src\compiler\Restler.Compiler\SwaggerVisitors.fs:line 819
   at Restler.Compiler.SwaggerVisitors.processProperty(String propertyName, JsonSchemaProperty property, FSharpOption`1 propertyPayloadExampleValue, Boolean generateFuzzablePayload, Boolean trackParameters, FSharpOption`1 jsonPropertyMaxDepth, FSharpList`1 parents, SchemaCache schemaCache, FSharpFunc`2 cont) in C:\_Projects\DCS-RFID-ZIN52-SecurityTesting\microsoft_restler_fuzzer\restler-fuzzer-main\src\compiler\Restler.Compiler\SwaggerVisitors.fs:line 492
   at Restler.Compiler.SwaggerVisitors.declaredPropertyParameters@610.Invoke(KeyValuePair`2 item) in C:\_Projects\DCS-RFID-ZIN52-SecurityTesting\microsoft_restler_fuzzer\restler-fuzzer-main\src\compiler\Restler.Compiler\SwaggerVisitors.fs:line 616
   at Microsoft.FSharp.Collections.Internal.IEnumerator.choose@171.System-Collections-IEnumerator-MoveNext() in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\seq.fs:line 179
   at Microsoft.FSharp.Core.CompilerServices.RuntimeHelpers.takeInner@266[T,TResult](ConcatEnumerator`2 x, Unit unitVar0) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\seqcore.fs:line 268
   at Microsoft.FSharp.Collections.SeqModule.oneStepTo@987[T](IEnumerable`1 source, List`1 prefix, FSharpRef`1 enumeratorR, Int32 i) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\seq.fs:line 996
   at Microsoft.FSharp.Collections.SeqModule.action@4164-1[T](IEnumerable`1 source, List`1 prefix, FSharpRef`1 enumeratorR, Int32 i, Unit unitVar0) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\seq.fs:line 1011
   at Microsoft.FSharp.Collections.SeqModule.result@1003.Invoke(Int32 i)
   at Microsoft.FSharp.Collections.Internal.IEnumerator.unfold@205.DoMoveNext(b& curr) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\seq.fs:line 207
   at Microsoft.FSharp.Collections.Internal.IEnumerator.MapEnumerator`1.System-Collections-IEnumerator-MoveNext() in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\seq.fs:line 68
   at Microsoft.FSharp.Collections.SeqModule.ToList[T](IEnumerable`1 source) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\seq.fs:line 546

My Input .yaml(swagger) have zero  error in   https://editor.swagger.io/
and even in https://github.com/p1c2u/openapi-spec-validator   i ahve no error's

what is causing exception in restler, compiler log line not showing much info on input file,, than compiler error hits
pls can anyone look in to this

**Comment by whjv46** [comment]
Any ideas on  what could cause this message?

**Comment by marina-p** [comment]
Hello @rbpc86 and @whjv46,

One condition that will cause this error is that the schema has a property with an empty name (not handled in RESTler).  Is there one present in your spec?  I have added more information to the exception (PR will be merged shortly) - if you update and re-run the repro, hopefully this will allow you to pinpoint which property is causing the error.

Thank you,

Marina
