### ISSUE TITLE
payloadbody checker error when using dynamic value generator

### ISSUE THREAD

**Issue by marina-p** [microsoft/restler-fuzzer#505]
As discussed in #504, the following exception is thrown when using dynamic value generators for fuzzable string with the payload body checker.

2022-04-03 14:52:32.708: Generation: 1 
Exception 'function' object is not iterable applying checker <checkers.payload_body_checker.PayloadBodyChecker object at 0x104b97c40>
Terminating garbage collection. Waiting for max 300 seconds.
Traceback (most recent call last):
  File "/Users/alex/workspace/restler-fuzzer/restler_bin/engine/engine/core/fuzzer.py", line 42, in run
    self._num_total_sequences = driver.generate_sequences(
  File "/Users/alex/workspace/restler-fuzzer/restler_bin/engine/engine/core/driver.py", line 700, in generate_sequences
    seq_collection = render(seq_collection, fuzzing_pool, checkers, generation, global_lock)
  File "/Users/alex/workspace/restler-fuzzer/restler_bin/engine/engine/core/driver.py", line 322, in render_sequential
    valid_renderings = render_one(seq_collection[ith], ith, checkers, generation, global_lock)
  File "/Users/alex/workspace/restler-fuzzer/restler_bin/engine/engine/core/driver.py", line 214, in render_one
    apply_checkers(checkers, renderings, global_lock)
  File "/Users/alex/workspace/restler-fuzzer/restler_bin/engine/engine/core/driver.py", line 150, in apply_checkers
    checker.apply(renderings, global_lock)
  File "/Users/alex/workspace/restler-fuzzer/restler_bin/engine/checkers/payload_body_checker.py", line 185, in apply
    self._run_feedback_fuzzing(last_request, body_schema_list)
  File "/Users/alex/workspace/restler-fuzzer/restler_bin/engine/checkers/payload_body_checker.py", line 622, in _run_feedback_fuzzing
    ignore = set(
TypeError: 'function' object is not iterable

**Comment by marina-p** [comment]
The payload body checker filters out the dictionary values for ```restler_fuzzable_string``` when calculating coverage metrics based on ```(error code, error message)```.  The issue above is that when a dynamic generator is specified instead of a static list, this filter can no longer be initialized once at the start of fuzzing.  Moreover, the filter does not address every type of property (e.g. custom payloads), so it is incomplete.

First, as a workaround, simply skip the dynamic generator when initializing the static list of strings to exclude from analysis as above.

The root cause fix should be addressed by either implementing a better bucketization scheme (similar to results analyzer), or by having the analysis exclude all fuzzables by traversing the initialized python grammar elements (similar to invalid value checker).
