### ISSUE TITLE
Unexpected initial token 'String' when populating object. Expected JSON object or array. 

### ISSUE THREAD

**Issue by marina-p** [microsoft/restler-fuzzer#555]
[painsAgains](https://github.com/painsAgains) commented [20 days ago](https://github.com/microsoft/restler-fuzzer/issues/477#issuecomment-1149405214)
Hello：
when I compile my OpenAPI file I also got a compile .
/home/target/Desktop/Restler/restler-fuzzer/restler_working_dir/Compile/:cat StrErr.txt

Unhandled exception. System.AggregateException: One or more errors occurred. (Unexpected initial token 'String' when populating object. Expected JSON object or array. Path 'definitions['io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.JSONSchemaProps'].properties.__referencePath', line 1, position 3231994.)
---> Newtonsoft.Json.JsonSerializationException: Unexpected initial token 'String' when populating object. Expected JSON object or array. Path 'definitions['io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.JSONSchemaProps'].properties.__referencePath', line 1, position 3231994.
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Populate(JsonReader reader, Object target)
at Newtonsoft.Json.Serialization.JsonSerializerProxy.PopulateInternal(JsonReader reader, Object target)
at Newtonsoft.Json.JsonSerializer.Populate(JsonReader reader, Object target)
at NJsonSchema.ExtensionDataDeserializationConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateDictionary(IDictionary dictionary, JsonReader reader, JsonDictionaryContract contract, JsonProperty containerProperty, String id)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Populate(JsonReader reader, Object target)
at Newtonsoft.Json.Serialization.JsonSerializerProxy.PopulateInternal(JsonReader reader, Object target)
at Newtonsoft.Json.JsonSerializer.Populate(JsonReader reader, Object target)
at NJsonSchema.ExtensionDataDeserializationConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateDictionary(IDictionary dictionary, JsonReader reader, JsonDictionaryContract contract, JsonProperty containerProperty, String id)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Populate(JsonReader reader, Object target)
at Newtonsoft.Json.Serialization.JsonSerializerProxy.PopulateInternal(JsonReader reader, Object target)
at Newtonsoft.Json.JsonSerializer.Populate(JsonReader reader, Object target)
at NJsonSchema.ExtensionDataDeserializationConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
at NJsonSchema.Infrastructure.JsonSchemaSerialization.FromJson[T](String json, IContractResolver contractResolver)
at NJsonSchema.Infrastructure.JsonSchemaSerialization.FromJsonAsync[T](String json, SchemaType schemaType, String documentPath, Func2 referenceResolverFactory, IContractResolver contractResolver) at NSwag.OpenApiDocument.FromJsonAsync(String data, String documentPath, SchemaType expectedSchemaType, Func2 referenceResolverFactory)
at NSwag.OpenApiDocument.FromFileAsync(String filePath)
--- End of inner exception stack trace ---
at Microsoft.FSharp.Control.AsyncResult1.Commit() in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 349 at Microsoft.FSharp.Control.AsyncPrimitives.RunSynchronouslyInCurrentThread[a](CancellationToken cancellationToken, FSharpAsync1 computation) in F:\workspace_work\1\s\src\fsharp\FSharp.Core\async.fs:line 882
at Microsoft.FSharp.Control.AsyncPrimitives.RunSynchronously[T](CancellationToken cancellationToken, FSharpAsync1 computation, FSharpOption1 timeout) in F:\workspace_work\1\s\src\fsharp\FSharp.Core\async.fs:line 890
at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T](FSharpAsync1 computation, FSharpOption1 timeout, FSharpOption1 cancellationToken) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 1154 at Restler.Workflow.swaggerDocs@91-1.Invoke(String fp) in /home/target/Desktop/Restler/restler-fuzzer/src/compiler/Restler.Compiler/Workflow.fs:line 91 at Microsoft.FSharp.Primitives.Basics.List.map[T,TResult](FSharpFunc2 mapping, FSharpList1 x) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\local.fs:line 248 at Microsoft.FSharp.Collections.ListModule.Map[T,TResult](FSharpFunc2 mapping, FSharpList1 list) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\list.fs:line 75 at Restler.Workflow.generateGrammarFromSwagger(String grammarOutputDirectoryPath, FSharpOption1 swaggerDoc, FSharpOption1 specMetadata, Config config) in /home/target/Desktop/Restler/restler-fuzzer/src/compiler/Restler.Compiler/Workflow.fs:line 91 at Restler.Workflow.generateRestlerGrammar(FSharpOption1 swaggerDoc, Config config) in /home/target/Desktop/Restler/restler-fuzzer/src/compiler/Restler.Compiler/Workflow.fs:line 275
at Program.main(String[] argv) in /home/target/Desktop/Restler/restler-fuzzer/src/compiler/Restler.CompilerExe/Program.fs:line 37

But when I checked the path in my OpenAPI file ,I did not find the key:__referencePath in 'io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.JSONSchemaProps'].properties.__referencePath".

My compile enviroment is dotnet 5.0 and python 3.8.

Really hope someone can help me

Thank you!

**Comment by marina-p** [comment]
I have reproduced the issue using the definition provided in #477.

**Comment by marina-p** [comment]
Hello @painsAgains,

Apologies for the delay.

The reason for this error is that the ```$ref``` in the ```io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.JSONSchemaProps``` definition is invalid (see $ref syntax on this page: https://swagger.io/docs/specification/using-ref/).
```
                    "$ref": {
                        "type": "string"
                    },
```

Once it is removed, hopefully your compilation will succeed.  (I had to remove a few other ```$refs``` in the definition you provided for the compilation to succeed, because they were not included.)

Thanks,

Marina

**Comment by painsAgains** [comment]
Thanks,it works!



发自我的iPhone


------------------ Original ------------------
From: marina-p ***@***.***&gt;
Date: Tue,Jun 28,2022 3:29 AM
To: microsoft/restler-fuzzer ***@***.***&gt;
Cc: painsAgains ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [microsoft/restler-fuzzer] Unexpected initial token 'String' whenpopulating object. Expected JSON object or array.  (Issue #555)





 
Hello @painsAgains,
 
Apologies for the delay.
 
The reason for this error is that the $ref in the io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.JSONSchemaProps definition is invalid (see $ref syntax on this page: https://swagger.io/docs/specification/using-ref/).
                     "$ref": {                         "type": "string"                     },  
Once it is removed, hopefully your compilation will succeed.  (I had to remove a few other $refs in the definition you provided for the compilation to succeed, because they were not included.)
 
Thanks,
 
Marina
