### ISSUE TITLE
error when compiling (via quick start)

### ISSUE THREAD

**Issue by aharpervc** [microsoft/restler-fuzzer#61]
After installing dotnet 3.1 sdk, rebuilding the program, and re-running the quick start script, I get this error:

```
$ python restler-quick-start.py --api_spec_path ../openapi.yaml --restler_drop_dir bin/
Log share was not specified.  Logs will not be uploaded.
Starting task Compile...

ERROR: Compiler failed. See logs in /home/aharper/restler_working_dir/Compile directory for more information. 

Task Compile failed.
Collecting logs...

ERROR: The RESTler grammar file path /home/aharper/restler_working_dir/Compile/grammar.py does not exist.
```

The log file:

```
Restler Information: 0 : Log share was not specified.  Logs will not be uploaded.
    DateTime=2020-11-17T15:53:06.3059771Z
Restler Information: 0 : Starting task Compile...
    DateTime=2020-11-17T15:53:06.3131157Z
Restler Information: 0 : Launching 'dotnet "/mnt/c/Users/aharper/workspace/api-v3/.restler/bin/restler/../compiler/Restler.CompilerExe.dll" "/home/aharper/restler_working_dir/Compile/config.json"'
    DateTime=2020-11-17T15:53:06.5334522Z
Restler Information: 0 : Process execution terminated in 00:00:00.7213000 with exit code 0x86: 'dotnet "/mnt/c/Users/aharper/workspace/api-v3/.restler/bin/restler/../compiler/Restler.CompilerExe.dll" "/home/aharper/restler_working_dir/Compile/config.json"'
    DateTime=2020-11-17T15:53:07.2638454Z
Restler Information: 0 : (7061) dotnet "/mnt/c/Users/aharper/workspace/api-v3/.restler/bin/restler/../compiler/Restler.CompilerExe.dll" "/home/aharper/restler_working_dir/Compile/config.json" exited with code: 134
    DateTime=2020-11-17T15:53:07.2706808Z
Restler Error: 0 : Compiler failed. See logs in /home/aharper/restler_working_dir/Compile directory for more information.
    DateTime=2020-11-17T15:53:07.2782879Z
Restler Information: 0 : Task Compile failed.
    DateTime=2020-11-17T15:53:07.2822032Z
Restler Information: 0 : Collecting logs...
    DateTime=2020-11-17T15:53:07.2879897Z
```

The path `.restler/bin/restler/../compiler/Restler.CompilerExe.dll` seems odd, but `.restler/bin/compiler/Restler.CompilerExe.dll` does exist, along with all the other compilation artifacts. So not sure what the problem is or what the next thing to check would be.

(side note: hard coding a working dir in my home folder isn't cool... it should either be configurable or relative to the process working dir).

**Comment by marina-p** [comment]
@aharpervc Thanks for the detailed feedback!  Can you please share the StdErr.txt log in ```/home/aharper/restler_working_dir/Compile```?

**Comment by marina-p** [comment]
Re: working dir in the home folder - absolutely, this is a bug, we will fix ASAP.  (This should have been created relative to the cwd). 

Re: configurability, we were trying to minimize the arguments required to the quick start script, which is why that configuration option wasn't added for our quick start scenario.

**Comment by aharpervc** [comment]
Haha okay I guess that error message wasn't clear on _which_ log file to look at...

I reduced my openapi.yaml file to a minimum repro for the same error, then re-ran the script.

```yaml
---
openapi: 3.0.3
info:
  title: example api
  version: 1.2.3
paths:
  "/test_endpoint_1":
    post:
      responses:
        '200':
          description: OK
          headers:
            X-API-Revision:
              required: true
              description: API Revision
              schema:
                type: string
```

There is a StdErr.txt which shows this:

```
Unhandled exception. System.AggregateException: One or more errors occurred. (Unexpected token while deserializing object: EndObject. Path 'paths['/test_endpoint_1'].post.responses.200.headers.X-API-Revision.schema', line 1, position 268.)
 ---> Newtonsoft.Json.JsonSerializationException: Unexpected token while deserializing object: EndObject. Path 'paths['/test_endpoint_1'].post.responses.200.headers.X-API-Revision.schema', line 1, position 268.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.Serialization.JsonSerializerProxy.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader)
   at NSwag.OpenApiPathItem.OpenApiPathItemConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateDictionary(IDictionary dictionary, JsonReader reader, JsonDictionaryContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, 
JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Populate(JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerProxy.PopulateInternal(JsonReader reader, Object target)
   at Newtonsoft.Json.JsonSerializer.Populate(JsonReader reader, Object target)
   at NJsonSchema.ExtensionDataDeserializationConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at NJsonSchema.Infrastructure.JsonSchemaSerialization.FromJson[T](String json, IContractResolver contractResolver)
   at NJsonSchema.Infrastructure.JsonSchemaSerialization.FromJsonAsync[T](String json, SchemaType schemaType, String documentPath, Func`2 referenceResolverFactory, IContractResolver contractResolver)
   at NSwag.OpenApiDocument.FromJsonAsync(String data, String documentPath, SchemaType expectedSchemaType, Func`2 referenceResolverFactory)
   at NSwag.OpenApiYamlDocument.FromYamlAsync(String data, String documentPath, SchemaType expectedSchemaType, Func`2 referenceResolverFactory)
   at NSwag.OpenApiYamlDocument.FromFileAsync(String filePath)
   --- End of inner exception stack trace ---
   at Microsoft.FSharp.Control.AsyncResult`1.Commit() in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 338
   at Microsoft.FSharp.Control.AsyncPrimitives.RunSynchronouslyInCurrentThread[a](CancellationToken cancellationToken, FSharpAsync`1 computation) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 870
   at Microsoft.FSharp.Control.AsyncPrimitives.RunSynchronously[T](CancellationToken cancellationToken, FSharpAsync`1 computation, FSharpOption`1 timeout) in 
F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 878
   at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T](FSharpAsync`1 computation, FSharpOption`1 timeout, FSharpOption`1 cancellationToken) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 1142
   at Restler.Workflow.swaggerDocs@88-1.Invoke(String fp) in /mnt/c/Users/aharper/workspace/api-v3/.restler/src/compiler/Restler.Compiler/Workflow.fs:line 88
   at Microsoft.FSharp.Primitives.Basics.List.map[T,TResult](FSharpFunc`2 mapping, FSharpList`1 x) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\local.fs:line 248
   at Microsoft.FSharp.Collections.ListModule.Map[T,TResult](FSharpFunc`2 mapping, FSharpList`1 list) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\list.fs:line 75
   at Restler.Workflow.generateGrammarFromSwagger(String grammarOutputDirectoryPath, FSharpOption`1 swaggerDoc, Config config) in /mnt/c/Users/aharper/workspace/api-v3/.restler/src/compiler/Restler.Compiler/Workflow.fs:line 88
   at Restler.Workflow.generateRestlerGrammar(FSharpOption`1 swaggerDoc, Config config) in /mnt/c/Users/aharper/workspace/api-v3/.restler/src/compiler/Restler.Compiler/Workflow.fs:line 233
   at Program.main(String[] argv) in /mnt/c/Users/aharper/workspace/api-v3/.restler/src/compiler/Restler.CompilerExe/Program.fs:line 37
```

**Comment by marina-p** [comment]
@aharpervc This is unfortunately a failure to parse the yaml by the underlying library (NSwag) we are using.   The root cause of this particular error is the ```required: true```.  As a workaround, if you remove the required, compilation succeeds.  

It looks like the library is expecting the below syntax for required schema properties:

```
      responses:
        '200':
          description: OK
          headers:
            X-API-Revision:
              description: API Revision
              schema:
                type: string
          **required:
            X-API-Revision**
```

We'd need to investigate further why this is not supported in NSWag.  If it's intentional or they decide not to fix it, we'd need to introduce a preprocessing step to remove these unsupported elements in order to successfully compile these specs.  (See `SwaggerSpecPreprocessor` for an example).

**Comment by aharpervc** [comment]
Odd, that definitely sounds like a bug/limitation of NSwag. Per the OpenAPI spec, [header objects](https://swagger.io/specification/#header-object) are [parameter objects](https://swagger.io/specification/#parameter-object) (with changes to name/in, so unrelated to this). Parameter objects define `required` as an optional boolean, so providing it with a `true` value should be acceptable.

**Comment by marina-p** [comment]
Linking open NSWag issue: https://github.com/RicoSuter/NSwag/issues/2928

**Comment by marina-p** [comment]
Workaround merged.
