### ISSUE TITLE
Exception substring not found applying checker

### ISSUE THREAD

**Issue by jbauernberger** [microsoft/restler-fuzzer#621]
### Description

running into some issues when trying to set up the installation to show my colleagues. The out of the box demo_server (with the swagger.json) compiles OK but running `fuzz`causes Restler to exit with errors: 

`ERROR: Restler engine failed. See logs in /home/joachim/src/elux_fuzz/Fuzz directory for more information.`

my python is 3.10.6 btw

EngineStdErr.txt is empty and `EngineStdOut.txt` has:

```
2022-09-01 13:13:21.618: Initializing: Garbage collection every 30 seconds.
2022-09-01 13:13:21.620: Generation: 1 
Invalid value generator random seed: 1662030801.7011344
2022-09-01 13:13:51.184: Generation: 2 
Exception substring not found applying checker <checkers.invalid_value_checker.InvalidValueChecker object at 0x7f482060ee30>
2022-09-01 13:13:51.508: Terminating garbage collection. Waiting for max 300 seconds. 
Traceback (most recent call last):
  File "/home/joachim/src/restler-fuzzer/restler_bin/engine/engine/core/fuzzer.py", line 43, in run
    self._num_total_sequences = driver.generate_sequences(
  File "/home/joachim/src/restler-fuzzer/restler_bin/engine/engine/core/driver.py", line 715, in generate_sequences
    seq_collection = render(seq_collection, fuzzing_pool, checkers, generation, global_lock,
  File "/home/joachim/src/restler-fuzzer/restler_bin/engine/engine/core/driver.py", line 335, in render_sequential
    valid_renderings = render_one(seq_collection[ith], ith, checkers, generation, global_lock, garbage_collector)
  File "/home/joachim/src/restler-fuzzer/restler_bin/engine/engine/core/driver.py", line 217, in render_one
    apply_checkers(checkers, renderings, global_lock)
  File "/home/joachim/src/restler-fuzzer/restler_bin/engine/engine/core/driver.py", line 151, in apply_checkers
    checker.apply(renderings, global_lock)
  File "/home/joachim/src/restler-fuzzer/restler_bin/engine/checkers/invalid_value_checker.py", line 317, in apply
    response = request_utilities.send_request_data(rendered_data)
  File "/home/joachim/src/restler-fuzzer/restler_bin/engine/engine/core/request_utilities.py", line 316, in send_request_data
    success, response = main_sock.sendRecv(rendered_data,
  File "/home/joachim/src/restler-fuzzer/restler_bin/engine/engine/transport_layer/messaging.py", line 110, in sendRecv
    self._sendRequest(message)
  File "/home/joachim/src/restler-fuzzer/restler_bin/engine/engine/transport_layer/messaging.py", line 187, in _sendRequest
    contentlen = len(message[_get_start_of_body(message):])
  File "/home/joachim/src/restler-fuzzer/restler_bin/engine/engine/transport_layer/messaging.py", line 180, in _get_start_of_body
    return _get_end_of_header(message) + len(DELIM)
  File "/home/joachim/src/restler-fuzzer/restler_bin/engine/engine/transport_layer/messaging.py", line 177, in _get_end_of_header
    return message.index(DELIM)
ValueError: substring not found
````

### Steps to reproduce

generic installation instructions trying to fuzz against demo_server

### Expected results

no exception

### Actual results

exception

### Environment details

Linux (Debian), python 3.10.6, dotnet 6.0.400, (restler 9.0.1 - latest from master branch) 

### engine_settings.json

```
{
  "per_resource_settings": {},
  "ignore_decoding_failures": true,
  "no_ssl": true,
  "time_budget": 6.00,
  "max_combinations": 6000,
  "checkers": {
    "useafterfree": {
      "mode": "exhaustive"
    },
    "leakagerule": {
      "mode": "exhaustive"
    },
    "invaliddynamicobject": {
      "mode": "exhaustive"
    },
    "payloadbody": {
      "mode": "exhaustive"
    },
    "resourcehierarchy": {
      "mode": "exhaustive"
    }
  }
}

```

**Comment by marina-p** [comment]
Hi @jbauernberger,

This is a regression, investigating ASAP.

Thanks,

Marina

**Comment by marina-p** [comment]
To work around this, you can disable the invalidvalue checker in `fuzz` mode (this checker was recently turned on by default):

**Comment by jbauernberger** [comment]
thanks @marina-p this eliminates the crash
