### ISSUE TITLE
Restler engine failed

### ISSUE THREAD

**Issue by jbauernberger** [microsoft/restler-fuzzer#650]
### Description

using the current latest from git main branch the engine crashes

````
2022-10-06 12:07:03.572: Initializing: Garbage collection every 30 seconds.
2022-10-06 12:07:03.610: Generation: 1 
2022-10-06 12:08:41.424: Terminating garbage collection. Waiting for max 300 seconds. 
Traceback (most recent call last):
  File "/home/joachim/src/restler-fuzzer/restler_bin/engine/engine/core/fuzzer.py", line 43, in run
    self._num_total_sequences = driver.generate_sequences(
  File "/home/joachim/src/restler-fuzzer/restler_bin/engine/engine/core/driver.py", line 711, in generate_sequences
    seq_collection = render_with_cache(seq_collection, fuzzing_pool, checkers,
  File "/home/joachim/src/restler-fuzzer/restler_bin/engine/engine/core/driver.py", line 462, in render_with_cache
    valid_renderings = render_one(prefix_seq_to_render, sequences_count, checkers, generation, global_lock, garbage_collector)
  File "/home/joachim/src/restler-fuzzer/restler_bin/engine/engine/core/driver.py", line 210, in render_one
    renderings = current_seq.render(candidate_values_pool, global_lock)
  File "/home/joachim/src/restler-fuzzer/restler_bin/engine/engine/core/sequences.py", line 557, in render
    response = request_utilities.send_request_data(rendered_data)
  File "/home/joachim/src/restler-fuzzer/restler_bin/engine/engine/core/request_utilities.py", line 316, in send_request_data
    success, response = main_sock.sendRecv(rendered_data,
  File "/home/joachim/src/restler-fuzzer/restler_bin/engine/engine/transport_layer/messaging.py", line 110, in sendRecv
    self._sendRequest(message)
  File "/home/joachim/src/restler-fuzzer/restler_bin/engine/engine/transport_layer/messaging.py", line 187, in _sendRequest
    contentlen = len(message[_get_start_of_body(message):])
  File "/home/joachim/src/restler-fuzzer/restler_bin/engine/engine/transport_layer/messaging.py", line 180, in _get_start_of_body
    return _get_end_of_header(message) + len(DELIM)
  File "/home/joachim/src/restler-fuzzer/restler_bin/engine/engine/transport_layer/messaging.py", line 177, in _get_end_of_header
    return message.index(DELIM)
ValueError: substring not found

````

the engine settings:

```
{
  "per_resource_settings": {},
  "ignore_decoding_failures": true,
  "no_ssl": false,
  "disable_cert_validation": true,
  "time_budget": 3.00,
  "max_combinations": 6000,
  "checkers": {
    "useafterfree": {
      "mode": "exhaustive"
    },
    "leakagerule": {
      "mode": "exhaustive"
    },
    "invaliddynamicobject": {
      "mode": "exhaustive"
    },
    "payloadbody": {
      "mode": "exhaustive"
    },
    "resourcehierarchy": {
      "mode": "exhaustive"
    }
  }
}

````

Python 3.10.6
dotnet 6.0.400
RESTler version: 9.1.0
Linux Debian 

### Steps to reproduce

...

thanks for any pointers

**Comment by marina-p** [comment]
Hi @jbauernberger,

This call stack unfortunately does not have enough info to diagnose the issue - I would need the grammar for the failing request.

From recent changes, my guess is that this could be due to commit c1ace0ce97e6906835a1f04f092d904c9f69335e.  If you cannot share the grammar, could you please try removing this commit locally and seeing if this resolves the crash?


Thanks,

Marina

**Comment by jbauernberger** [comment]
Hi @marina-p, thanks for getting back. Indeed I'm unfortunately unable to share the grammar :( ... trying to go back to c1ace0c didn't solve the issue sadly.

**Comment by jbauernberger** [comment]
@marina-p I've found a way to reduce the openapi spec / grammar so that no relevant info is shared but still be able to generate the crash. The grammar json/py contain:

```
{
  "Requests": [
    {
      "id": {
        "endpoint": "/Ping",
        "method": "Post"
      },
      "method": "Post",
      "basePath": "",
      "path": [
        {
          "Constant": [
            "String",
            "Ping"
          ]
        }
      ],
      "queryParameters": [
        [
          "Schema",
          {
            "ParameterList": []
          }
        ]
      ],
      "bodyParameters": [
        [
          "Schema",
          {
            "ParameterList": [
              {
                "name": "__body__",
                "payload": {
                  "LeafNode": {
                    "name": "",
                    "payload": {
                      "Fuzzable": {
                        "primitiveType": "String",
                        "defaultValue": "fuzzstring",
                        "exampleValue": "\\\"\\\""
                      }
                    },
                    "isRequired": true,
                    "isReadOnly": false
                  }
                }
              }
            ]
          }
        ]
      ],
      "headerParameters": [
        [
          "Schema",
          {
            "ParameterList": [
              {
                "name": "Content-Type",
                "payload": {
                  "LeafNode": {
                    "name": "",
                    "payload": {
                      "Fuzzable": {
                        "primitiveType": "String",
                        "defaultValue": "fuzzstring",
                        "exampleValue": "application/json"
                      }
                    },
                    "isRequired": false,
                    "isReadOnly": false
                  }
                }
              }
            ]
          }
        ],
        [
          "DictionaryCustomPayload",
          {
            "ParameterList": [
              {
                "name": "Content-Type",
                "payload": {
                  "LeafNode": {
                    "name": "",
                    "payload": {
                      "Constant": [
                        "String",
                        "application/json"
                      ]
                    },
                    "isRequired": true,
                    "isReadOnly": false
                  }
                }
              }
            ]
          }
        ]
      ],
      "token": "Refreshable",
      "headers": [
        [
          "Accept",
          "application/json"
        ],
        [
          "Host",
          "{{fums-reporting}}"
        ]
      ],
      "httpVersion": "1.1",
      "requestMetadata": {
        "isLongRunningOperation": false
      }
    },
    {
      "id": {
        "endpoint": "/Ping",
        "method": "Get"
      },
      "method": "Get",
      "basePath": "",
      "path": [
        {
          "Constant": [
            "String",
            "Ping"
          ]
        }
      ],
      "queryParameters": [
        [
          "Schema",
          {
            "ParameterList": []
          }
        ]
      ],
      "bodyParameters": [
        [
          "Schema",
          {
            "ParameterList": []
          }
        ]
      ],
      "headerParameters": [
        [
          "Schema",
          {
            "ParameterList": [
              {
                "name": "Content-Type",
                "payload": {
                  "LeafNode": {
                    "name": "",
                    "payload": {
                      "Fuzzable": {
                        "primitiveType": "String",
                        "defaultValue": "fuzzstring",
                        "exampleValue": "application/json"
                      }
                    },
                    "isRequired": false,
                    "isReadOnly": false
                  }
                }
              }
            ]
          }
        ],
        [
          "DictionaryCustomPayload",
          {
            "ParameterList": []
          }
        ]
      ],
      "token": "Refreshable",
      "headers": [
        [
          "Accept",
          "application/json"
        ],
        [
          "Host",
          "{{fums-reporting}}"
        ]
      ],
      "httpVersion": "1.1",
      "requestMetadata": {
        "isLongRunningOperation": false
      }
    }
  ]
}
```

and

```
""" THIS IS AN AUTOMATICALLY GENERATED FILE!"""
from __future__ import print_function
import json
from engine import primitives
from engine.core import requests
from engine.errors import ResponseParsingException
from engine import dependencies
req_collection = requests.RequestCollection([])
# Endpoint: /Ping, method: Post
request = requests.Request([
    primitives.restler_static_string("POST "),
    primitives.restler_basepath(""),
    primitives.restler_static_string("/"),
    primitives.restler_static_string("Ping"),
    primitives.restler_static_string(" HTTP/1.1\r\n"),
    primitives.restler_static_string("Accept: application/json\r\n"),
    primitives.restler_static_string("Host: {{fums-reporting}}\r\n"),
    primitives.restler_static_string("Content-Type: "),
    primitives.restler_fuzzable_string("fuzzstring", quoted=False, examples=["application/json"]),
    primitives.restler_static_string("\r\n"),
    primitives.restler_static_string("Content-Type: "),
    primitives.restler_static_string("application/json"),
    primitives.restler_static_string("\r\n"),
    primitives.restler_refreshable_authentication_token("authentication_token_tag"),
    primitives.restler_static_string("\r\n"),
    primitives.restler_fuzzable_string("fuzzstring", quoted=True, examples=["""\"\""""]),
    primitives.restler_static_string("\r\n"),

],
requestId="/Ping"
)
req_collection.add_request(request)

# Endpoint: /Ping, method: Get
request = requests.Request([
    primitives.restler_static_string("GET "),
    primitives.restler_basepath(""),
    primitives.restler_static_string("/"),
    primitives.restler_static_string("Ping"),
    primitives.restler_static_string(" HTTP/1.1\r\n"),
    primitives.restler_static_string("Accept: application/json\r\n"),
    primitives.restler_static_string("Host: {{fums-reporting}}\r\n"),
    primitives.restler_static_string("Content-Type: "),
    primitives.restler_fuzzable_string("fuzzstring", quoted=False, examples=["application/json"]),
    primitives.restler_static_string("\r\n"),
    primitives.restler_refreshable_authentication_token("authentication_token_tag"),
    primitives.restler_static_string("\r\n"),

],
requestId="/Ping"
)
req_collection.add_request(request)

```

**Comment by marina-p** [comment]
Hello @jbauernberger,

Thank you, the repro was very helpful.   The fix is merged.

Thanks,

Marina

**Comment by jbauernberger** [comment]
thanks @marina-p - this solved it :)
