### ISSUE TITLE
NullReferenceException when running test

### ISSUE THREAD

**Issue by lorg** [microsoft/restler-fuzzer#685]
### Description

While trying to run restler on the spec of a large project, I ran into a nullreference exception. Here is the command:
`dotnet "/Users/ [...snip...] /fuzzing/restler-fuzzer/restler_bin/restler/Restler.dll"
test --grammar_file "Compile/grammar.py" --dictionary_file "Compile/dict.json" --settings "Compile/engine_settings.json"`

Here is the output:
```
Starting task Test...
Using python: 'python3' (Python 3.10.8)
Request coverage (successful / total): 0 / 42
Attempted requests: 0 / 42
No bugs were found.

ERROR: Task Test failed.  Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Restler.Driver.SpecCoverage.getEscapedString@320-1.Invoke(String state, Tuple`2 tupledArg) in /Users/ [ ....snip...] /fuzzing/restler-fuzzer/src/driver/SpecCoverage.fs:line 321
   at Microsoft.FSharp.Collections.ListModule.Fold[T,TState](FSharpFunc`2 folder, TState state, FSharpList`1 list) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\list.fs:line 222
   at Restler.Driver.SpecCoverage.getRequestResponseText@316(RequestCoverageData reqData) in /Users/ [ .... snip ... ] /fuzzing/restler-fuzzer/src/driver/SpecCoverage.fs:line 326
   at Restler.Driver.SpecCoverage.getRequestSequence(FSharpList`1 reqCoverageData, FSharpMap`2 renderingToReqCovMap, RequestCoverageData renderedCombination) in /Users/ [ .... snip ... ] /fuzzing/restler-fuzzer/src/driver/SpecCoverage.fs:line 343
   at Restler.Driver.SpecCoverage.combinations@421.Invoke(RequestCoverageData renderedCombination)
   at Microsoft.FSharp.Collections.Internal.IEnumerator.map@75.DoMoveNext(b& curr) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\seq.fs:line 78
   at Microsoft.FSharp.Collections.Internal.IEnumerator.MapEnumerator`1.System-Collections-IEnumerator-MoveNext() in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\seq.fs:line 64
   at Microsoft.FSharp.Collections.SeqModule.ToList[T](IEnumerable`1 source)
   at Restler.Driver.SpecCoverage.getFailedRequestSequences@417.Invoke(Tuple`3 tupledArg) in /Users/ [ .... snip ... ] /fuzzing/restler-fuzzer/src/driver/SpecCoverage.fs:line 419
   at Microsoft.FSharp.Collections.Internal.IEnumerator.map@75.DoMoveNext(b& curr) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\seq.fs:line 78
   at Microsoft.FSharp.Collections.Internal.IEnumerator.MapEnumerator`1.System-Collections-IEnumerator-MoveNext() in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\seq.fs:line 64
   at Restler.Driver.SpecCoverage.printFailedRequestSequences(IEnumerable`1 failedRequests, TextWriter writer) in /Users/ [ .... snip ... ] /fuzzing/restler-fuzzer/src/driver/SpecCoverage.fs:line 452
   at Restler.Driver.TaskResults.generateApiCoverageReport(String taskWorkingDirectory) in /Users/ [ .... snip ... ] /fuzzing/restler-fuzzer/src/driver/TaskResults.fs:line 90
   at Program.runRestlerTask@883-20.Invoke(FSharpOption`1 analyzerResult) in /Users/ [ .... snip ... ] /fuzzing/restler-fuzzer/src/driver/Program.fs:line 901
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvokeNoHijackCheck[a,b](AsyncActivation`1 ctxt, FSharpFunc`2 userCode, b result1) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 416
   at Program.runRestlerTask@879-17.Invoke(AsyncActivation`1 ctxt)
   at Program.Fuzz.runResultsAnalyzer@357-7.Invoke(AsyncActivation`1 ctxt)
   at Microsoft.FSharp.Control.AsyncPrimitives.unitAsync@589.Invoke(AsyncActivation`1 ctxt) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 589
   at Microsoft.FSharpLu.Diagnostics.Process.startProcessAsync@290-49.Invoke(AsyncActivation`1 ctxt)
   at Microsoft.FSharp.Control.AsyncPrimitives.unitAsync@589.Invoke(AsyncActivation`1 ctxt) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 589
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 109

Task Test failed.
Collecting logs...
```

### Steps to reproduce

* Try the quick start on the following YAML file:
** https://piiano.com/docs/assets/files/openapi-524e92cdb4dc7881e74ee8ee2feb721f.yaml
* I am running this on Piiano Vault, see here for details: https://piiano.com/docs/guides/get-started/

### Environment details

Running on Mac M1 with Ventura 13.1, Python 3.10.8, dotnet version 6.10.405

**Comment by lorg** [comment]
Better how to reproduce:

* Start the demo server
* Run the quickstart script - all ok
* Copy the command from the quickstart script
* `cd restler_working_dir`
* Run the command from the quickstart script:
```
dotnet "/Users/[ ... snip ...]/fuzzing/restler-fuzzer/restler_bin/restler/Restler.dll" test --grammar_file "Compile/grammar.py" --dictionary_file "Compile/dict.json" --settings "Compile/engine_settings.json"
```

**Comment by marina-p** [comment]
Hello @lorg,

Thank you for reporting this.

I'm having trouble getting this to reproduce using the directions and spec file you provided (I'm getting a different error from the engine before RESTler ever reaches this code), but I have put in a possible fix based on your call stack.  Could you please try the code in the `mp/null` branch and let me know if the crash goes away / RESTler is successful?

Thanks,

Marina

**Comment by marina-p** [comment]
Hello @lorg,

Nevermind, I was able to reproduce your call stack with your additional instructions on quick start.  Working on the fix, will update when it's pushed to the above branch.

Thanks,

Marina

**Comment by lorg** [comment]
@marina-p I hope you and all your colleagues are well 🙏

**Comment by marina-p** [comment]
Closed by #686

**Comment by lorg** [comment]
@marina-p this still reproduces for me on main, are you sure this was fixed?

**Comment by marina-p** [comment]
Hello @lorg,

I no longer see the issue with the original repro.  Can you please confirm you reproduce with the latest main (in particular, with PR #686 merged)?  If yes, would it be possible for you to share the speccov-min.json file from your logs?

Thanks,

Marina
