### ISSUE TITLE
Does restler fuzzer only supports API spec 2.0? 

### ISSUE THREAD

**Issue by lipeng28** [microsoft/restler-fuzzer#722]
### Description

The compilation of a API spec 3.0 failed, so I asked this question. Thanks!

**Comment by marina-p** [comment]
Hello @lipeng28,

RESTler does support OpenAPI 3.0.  Could you please share more details on the error (e.g. the call stack)?  

Thank you,

Marina

**Comment by lipeng28** [comment]
Hi @marina-p,
The detailed compilation error is shown below, I used the command "Rester compile --api_spec ..." 

Unhandled exception. System.NotImplementedException: Objects in query parameters are not supported yet.
   at Restler.CodeGenerator.Python.formatNestedQueryParameter@306(RequestParameter requestParameter, String parameterName, NestedType propertyType, FSharpOption`1 namePayloadSeq, IEnumerable`1 innerProperties) in /src/compiler/Restler.Compiler/CodeGenerator.fs:line 315
   at Restler.CodeGenerator.Python.generatePythonParameter@417-1.Invoke(Int32 level, InnerProperty p, IEnumerable`1 innerProperties) in /src/compiler/Restler.Compiler/CodeGenerator.fs:line 438
   at Restler.Grammar.Tree.processTree@34-1.Invoke(IEnumerable`1 ts) in /src/compiler/Restler.Compiler/Grammar.fs:line 35
   at Restler.Grammar.Tree.cataCtx[a,LeafData,r,INodeData](FSharpFunc`2 fLeaf, FSharpFunc`2 fNode, FSharpFunc`2 fCtx, a ctx, Tree`2 tree) in /src/compiler/Restler.Compiler/Grammar.fs:line 37
   at Restler.CodeGenerator.Python.parameters@505-3.Invoke(RequestParameter p) in /src/compiler/Restler.Compiler/CodeGenerator.fs:line 505
   at Microsoft.FSharp.Primitives.Basics.List.map[T,TResult](FSharpFunc`2 mapping, FSharpList`1 x) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\local.fs:line 248
   at Restler.CodeGenerator.Python.generatePythonFromRequestElement(Boolean includeOptionalParameters, RequestId requestId, RequestElement e) in /src/compiler/Restler.Compiler/CodeGenerator.fs:line 504
   at Restler.CodeGenerator.Python.generatePythonFromRequest@771.Invoke(RequestElement requestElement) in /src/compiler/Restler.Compiler/CodeGenerator.fs:line 772
   at Restler.CodeGenerator.Python.generatePythonFromRequest(Request request, Boolean includeOptionalParameters, Boolean mergeStaticStrings) in /src/compiler/Restler.Compiler/CodeGenerator.fs:line 770
   at Restler.CodeGenerator.Python.generatePythonRequest@1225(Boolean includeOptionalParameters, FSharpFunc`2 formatRestlerPrimitive, Request request) in /src/compiler/Restler.Compiler/CodeGenerator.fs:line 1226
   at Restler.CodeGenerator.Python.getRequests@1253.Invoke(Request r) in /src/compiler/Restler.Compiler/CodeGenerator.fs:line 1253
   at Microsoft.FSharp.Primitives.Basics.List.mapToFreshConsTail[a,b](FSharpList`1 cons, FSharpFunc`2 f, FSharpList`1 x) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\local.fs:line 241
   at Microsoft.FSharp.Primitives.Basics.List.map[T,TResult](FSharpFunc`2 mapping, FSharpList`1 x) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\local.fs:line 251
   at Microsoft.FSharp.Collections.ListModule.Map[T,TResult](FSharpFunc`2 mapping, FSharpList`1 list) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\list.fs:line 75
   at Restler.CodeGenerator.Python.generatePythonGrammar@1267.GenerateNext(IEnumerable`1& next) in /src/compiler/Restler.Compiler/CodeGenerator.fs:line 1274
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl() in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\seqcore.fs:line 371
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.System-Collections-IEnumerator-MoveNext() in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\seqcore.fs:line 403
   at Microsoft.FSharp.Collections.SeqModule.ToList[T](IEnumerable`1 source) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\seq.fs:line 546
   at Restler.CodeGenerator.Python.generateCode(GrammarDefinition grammar, Boolean includeOptionalParameters, FSharpFunc`2 write) in /src/compiler/Restler.Compiler/CodeGenerator.fs:line 1299
   at Restler.Workflow.generatePython(String grammarOutputDirectoryPath, Config config, GrammarDefinition grammar) in /src/compiler/Restler.Compiler/Workflow.fs:line 31
   at Restler.Workflow.generateRestlerGrammar(FSharpOption`1 swaggerDoc, Config config) in /src/compiler/Restler.Compiler/Workflow.fs:line 296
   at Program.main(String[] argv) in /src/compiler/Restler.CompilerExe/Program.fs:line 43

**Comment by marina-p** [comment]
Hello @lipeng28,

Apologies for the delay in replying.  This failure is due to a particular feature RESTler does not support yet (regardless of OpenAPI version) - it only supports primitive types for query parameters, not objects with embedded parameters.  If you could include an example of the query with objects from your spec, that would help prioritize this feature.

Related issue: #477 

Thanks,

Marina

**Comment by Kyzminyarik** [comment]
Good afternoon, faced with a similar problem, a solution could not be found?

**Comment by squidfact** [comment]
Hello, added a initial support for nested object in query parameters.
